### ISSUE TITLE
Typo in getBalance() method

### ISSUE THREAD

**Issue by DEADPXLZ** [Berry-Pool/nami-wallet#10]
1. Enable wallet via **cardano.enable()**
2. Access the wallet balance via **cardano.getBalance()**

Result: Accessing the getBalance() method returns an error due to typo in method name (see attachment)

<img width="167" alt="Screen Shot 2021-07-12 at 4 34 23 PM" src="https://user-images.githubusercontent.com/83417674/125296575-1a59e880-e32f-11eb-9e90-af9e5cf929fd.png">

**Comment by alessandrokonrad** [comment]
Thank you, not sure how I could oversee that!

**Comment by DEADPXLZ** [comment]
No problemo, it happens! I was excited to play around with this!🙌

**Comment by alessandrokonrad** [comment]
Awesome! :)
