### ISSUE TITLE
UI Enhancement

### ISSUE THREAD

**Issue by BlakeBrown** [Berry-Pool/nami-wallet#101]
I was buying this asset on jpg.store when I noticed that the UI said I was getting 1750 ADA, rather than deducting 250 ADA from my wallet to pay for the NFT. I think if there's a UTXO that's going back to the user's address, we should exclude this from the total shown to the user. Thoughts?

![image](https://user-images.githubusercontent.com/6283620/142144262-a3cd7991-3a2b-45b5-a8e3-65f0c73888e2.png)

PS. Sorry I've reported several issues in the past few days and am beginning to feel bad 😅 However, our store is bringing a lot of new users to Nami and I really want them to have the best user experience possible. Please let me know if your bandwidth is full and if so, I can try to fix these issues myself when I have the time. Thank you!

**Comment by alessandrokonrad** [comment]
Hey sure no problem just report everything you have.
Actually Nami handles that behaviour ignoring UTxOs that go back to the wallet itself. Are you sure it's right on your side? I just checked your marketplace I don't see that happening to me

**Comment by BlakeBrown** [comment]
Thanks for the reply... seems to be working again, but I have no idea why. Will let you know if this shows up again!
