### ISSUE TITLE
Collateral : Invalid collateral used

### ISSUE THREAD

**Issue by waalge** [Berry-Pool/nami-wallet#105]
I want to sign a transaction that I am not providing collateral for - someone else is. 
They can sign, but I can't

https://github.com/Berry-Pool/nami-wallet/blob/400637882f08b2efc9299396d37eff76934ab3ea/src/ui/app/pages/signTx.jsx#L359

Any thoughts?

**Comment by alessandrokonrad** [comment]
The idea here was to restrict the dApp to choose other UTxOs than the set collateral UTxO for security reasons.
Having others providing the collateral is something we could allow tho.

**Comment by alessandrokonrad** [comment]
Yes it's safe enough, wasn't really aware of such uses cases with shared collateral. I'm gonna loose this a little bit to allow such cases.

**Comment by waalge** [comment]
Do you want a PR for this?

**Comment by alessandrokonrad** [comment]
https://github.com/Berry-Pool/nami-wallet/commit/c7a045d6c059a92d481237eba405589f6155ef23

**Comment by waalge** [comment]
Thanks so much.  
I've had just a chance to try that but didn't get very far. 
For some context, it took a very long time for me to resolve issues in building nami on node v16.9.
Mainly with node-sass and node-gyp 
(Are you using v14?) 
So these new problems might be related to this.

I can build, then open the extension. import wallet > type in sentence > type in name, password, password repeat, and on submit hit this: 
```
mainPopup.bundle.js:270257 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
```
Referring to this line
```
var mnemonicFromObject = function mnemonicFromObject(mnemonicMap) {
  return Object.keys(mnemonicMap).reduce(function (acc, key) {
    return acc ? acc + ' ' + mnemonicMap[key] : acc + mnemonicMap[key];
  }, '');
};
```

**Comment by waalge** [comment]
... 

Although the app seems to hang, closing the browser, relaunching, and reopening the app is then logged in. 

This then works! Amazing. 

It still requires the user to set their collateral even if the tx they are signing requires it or not. 
But ... something everyone can live with.

**Comment by alessandrokonrad** [comment]
> Thanks so much. I've had just a chance to try that but didn't get very far. For some context, it took a very long time for me to resolve issues in building nami on node v16.9. Mainly with node-sass and node-gyp (Are you using v14?) So these new problems might be related to this.
> 
> I can build, then open the extension. import wallet > type in sentence > type in name, password, password repeat, and on submit hit this:
> 
> ```
> mainPopup.bundle.js:270257 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
>     at Function.keys (<anonymous>)
> ```
> 
> Referring to this line
> 
> ```
> var mnemonicFromObject = function mnemonicFromObject(mnemonicMap) {
>   return Object.keys(mnemonicMap).reduce(function (acc, key) {
>     return acc ? acc + ' ' + mnemonicMap[key] : acc + mnemonicMap[key];
>   }, '');
> };
> ```

That's strange. Yes I build nami with Node v14.17.3

**Comment by alessandrokonrad** [comment]
> It still requires the user to set their collateral even if the tx they are signing requires it or not.

Is this really the case? I actually loop over all own utxos now and only if the collateral matches one of the user's utxos, then it should check if collateral is even set

**Comment by waalge** [comment]
Maybe not, but it seemed to be for me. I don't think I've changed anything that would have effected this. But even if it does, its fine - it can now do multisig which is great
