### ISSUE TITLE
Asset and Collectibles sorting

### ISSUE THREAD

**Issue by BoladoLimited** [Berry-Pool/nami-wallet#107]
Read on twitter that if a token has "721" json key is considered a collectible, but even the ones who doesn't have, is being placed on collectibles tab.

Cardax Token Metadata (has a json structure on metadata):
<img width="204" alt="Screen Shot 2021-11-23 at 19 20 53" src="https://user-images.githubusercontent.com/74077743/143138414-936060e3-e53b-44e7-a28e-063a78b0fbaf.png">

Hosky (has a json structure but no "721" key:
<img width="344" alt="Screen Shot 2021-11-23 at 19 22 53" src="https://user-images.githubusercontent.com/74077743/143138630-b07c0798-3d38-40a6-9165-40e502ac2953.png">

Judging by the pattern, any FT that has a json structure seems to be being placed on collectibles tab, I got the metadata with the pool.pm lookup, may be wrong.

**Comment by alessandrokonrad** [comment]
Hosky clearly has the 721 label. Check it on cardanoscan:
https://cardanoscan.io/transaction/1e0612fbd127baddfcd555706de96b46c4d4363ac78c73ab4dee6e6a7bf61fe9?tab=metadata

I'm not sure about the other asset, do you have the asset ID? But I'm pretty sure it has it as well. pool.pm may leave out top level keys.

**Comment by BoladoLimited** [comment]
True that, I got bamboozled, checking the asset id of CARDAX ( asset1s433jdc6gdjryekuyzr0faaw7nyr5dq50f2k9k ) I can see the complete metadata.

**Comment by alessandrokonrad** [comment]
https://github.com/cardano-foundation/CIPs/pull/137
There is this open CIP for normal tokens.

**Comment by BoladoLimited** [comment]
> [cardano-foundation/CIPs#137](https://github.com/cardano-foundation/CIPs/pull/137) There is this open CIP for normal tokens.

Awesome, thanks Alessandro for clearing things up, closing this now.
