### ISSUE TITLE
Wallet hard crash when using big num

### ISSUE THREAD

**Issue by pascallapointe** [Berry-Pool/nami-wallet#108]
User reported wallet hard crash when using high assets value.
Crashed with 40,000,000,000 $Hosky and 6,000,000,000 $Hosky.

PC restart required to open Nami again.

**Comment by alessandrokonrad** [comment]
<img width="377" alt="Screenshot 2021-11-24 at 09 38 39" src="https://user-images.githubusercontent.com/35738310/143203493-d83a8f60-0ed7-4ca7-9451-0ce4d826e2f2.png">

I just tested it with an absurd amount, was no problem at all. You may have to test it as well, maybe I'm missing something. I think with an 8-bit toaster it probably doesn't work.

**Comment by pascallapointe** [comment]
Will try it on my old 16bits SNES tonight.

Joke appart, looks like we didn't forgot any BigInt.
I will test it too with the user UTxO set just to be sure it doesn't hide something else and close the issue if I can't makes it crash.

**Comment by pascallapointe** [comment]
The issue have been found to be more related to the uncommon UTxO distribution.
(1 assets numbered in billions split on over 700 separate utxos)
Could not reproduced the exact same behaviour on our environment, but asking for over the maximum amount did cause what looks like an infinite loops or really heavy calculation.

Optimization could be possible if the issue represent itself in the future.
