### ISSUE TITLE
[Nami Wallet Chrome Extension] Wallet can't finish loading assets (in both testnet and mainnet)

### ISSUE THREAD

**Issue by kazunetakeda25** [Berry-Pool/nami-wallet#109]
Platform: Linux
Browser: Chrome

Screenshot:
![image](https://user-images.githubusercontent.com/58710601/143407660-0bea230c-dd61-40e8-aff7-788e11ec6e1a.png)

**Comment by alessandrokonrad** [comment]
Hey, so it's stuck at loading? Do you have a few more details maybe?

**Comment by kazunetakeda25** [comment]
I can see why it was stuck. I just saw chrome extension got updated.
Now it is working fine.

**Comment by ahmednaufil** [comment]
Mine just does this 
![Screenshot from 2024-02-21 16-10-27](https://github.com/input-output-hk/nami/assets/88075199/36246bd8-d5d5-44be-b7cb-f33706d5defd)
