### ISSUE TITLE
npm install: make: error: unable to find utility "make", not a developer tool or in PATH

### ISSUE THREAD

**Issue by ilyaLibin** [Berry-Pool/nami-wallet#110]
Please advise
NODE VERSION v12.16.2
NPM version 7.20.3
![image](https://user-images.githubusercontent.com/12880486/143440766-5b1f75ad-19b7-46cd-840a-1f07239b3002.png)

npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'ipfs@0.56.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'ipfs-http-client@51.0.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0', npm: '>=3.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'ipfs-repo@11.0.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'ipfs-unixfs@5.0.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'ipfs-unixfs-exporter@6.0.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'ipfs-unixfs-importer@8.0.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'is-ipfs@6.0.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0', npm: '>=6.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'libp2p@0.32.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'libp2p-bootstrap@0.13.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'libp2p-kad-dht@0.23.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'libp2p-record@0.10.4',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'libp2p-tcp@0.17.1',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'libp2p-webrtc-star@0.23.0',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'peer-id@0.15.2',
npm WARN EBADENGINE   required: { node: '>=14.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.16.2', npm: '7.20.3' }
npm WARN EBADENGINE }
npm ERR! code 1
npm ERR! path /Users/ilyalibin/Dev/nami-wallet/node_modules/ursa-optional
npm ERR! command failed
npm ERR! command sh -c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@12.16.2 | darwin | x64
npm ERR! gyp http GET https://nodejs.org/download/release/v12.16.2/node-v12.16.2-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v12.16.2/node-v12.16.2-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v12.16.2/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v12.16.2/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python2
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/ilyalibin/Dev/nami-wallet/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/ilyalibin/Dev/nami-wallet/node_modules/ursa-optional/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/ilyalibin/Dev/nami-wallet/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/ilyalibin/.node-gyp/12.16.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/ilyalibin/.node-gyp/12.16.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/ilyalibin/Dev/nami-wallet/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/ilyalibin/.node-gyp/12.16.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Users/ilyalibin/Dev/nami-wallet/node_modules/ursa-optional',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! sh: line 1:  7273 Bus error: 10           /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk '' -find make 2> /dev/null
npm ERR! make: error: unable to find utility "make", not a developer tool or in PATH
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 72
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/ilyalibin/Dev/nami-wallet/node_modules/node-gyp/lib/build.js:262:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:310:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
npm ERR! gyp ERR! System Darwin 20.6.0
npm ERR! gyp ERR! command "/usr/local/bin/node" "/Users/ilyalibin/Dev/nami-wallet/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /Users/ilyalibin/Dev/nami-wallet/node_modules/ursa-optional
npm ERR! gyp ERR! node -v v12.16.2
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ilyalibin/.npm/_logs/2021-11-25T12_14_46_366Z-debug.log

**Comment by sadasant** [comment]
@ilyaLibin hello hello 👋 I might be able to help you. What’s the output of `which make` if you run it in a terminal?

**Comment by waalge** [comment]
Might want to bump your node version to v14 too. 
node-gyp and node-sass seemed sensitive to me using v16 (rather than v14 which its being developed with. )

**Comment by ilyaLibin** [comment]
@sadasant Hi Daniel, sorry for the late response. Here is what I get
![image](https://user-images.githubusercontent.com/12880486/144234186-47e51025-9724-4c84-ae2c-26064a57948d.png)

**Comment by sadasant** [comment]
> BTW does Nami wallet forking Yoroi, or uses Yoroi setup in any form?

Nope I don’t think so.

**Comment by sadasant** [comment]
So, as far as I can tell, failing to find `make` could be either that: Node is starting a shell session incorrectly (either Nami or some dependency. But I don’t think Nami does anything special here.) or that XCode is having an environmental issue.

I am trying to investigate in the dependencies of Nami to see if anyone has experienced a similar issue.

In the mean time, I also found these steps: https://stackoverflow.com/a/60426451 They could help ensure that the environment is correctly set. Keep in mind that this answer is from February of 2020! So the versions might not be accurate.

Also, @waalge ’s suggestion to update to the latest Node.js could potentially fix this problem as well!

**Comment by ilyaLibin** [comment]
@sadasant Thank you very much, those steps did help!

**Comment by sadasant** [comment]
@ilyaLibin awesome!

If you were able to solve the problem, please close this issue. Thank you for reaching out! You’re welcome here anytime.
