### ISSUE TITLE
High failure rate of submitted transactions

### ISSUE THREAD

**Issue by BlakeBrown** [Berry-Pool/nami-wallet#111]
Hi Ales,

I've noticed a higher than usual failure rate for transactions submitted through Nami that never actually make it into a block. 

Anecdotally, this seems to occur more frequently when submitting several transactions right after one another.

Do you have any ideas why this might be happening?

https://www.jpg.store/user/addr1qym9vpaapk95ugp3mzec4kqxp2fp6ek5l8f9tdfrqg5est5nnc3snw25xvqytmhgu0zg7gg6vlg74gtpc356d7jkpn6qamlkuq?tab=activity
![image](https://user-images.githubusercontent.com/6283620/143498775-2ef52dfd-28ba-4b16-89de-ba688421cdc8.png)

**Comment by alessandrokonrad** [comment]
Hey, do you submit the transactions through the `submitTx` endpoint of Nami?
You mean submitting multiple transactions from the same wallet? If so make sure to no reuse the same utxos that are currently in pending state. Or wait until the user's transaction went through and then allow him first to make another one.

**Comment by BlakeBrown** [comment]
Thanks that makes a ton of sense, we definitely are re-using UTXOs. I'll do some thinking about which solution we should implement.

What are your thoughts on Nami having a `getAvailableUTXOs()` method? Just wondering because I could definitely see other dApps running into this same problem.

This problem is really interesting too because it depends on how Nami combines UTXOs. For our dApp, ideally Nami would always keep NFT UTXOs separated ( 1 NFT = 1 UTXO) so that there's never any contention when listing assets. Is the only downside to this just higher fees for the user?

**Comment by alessandrokonrad** [comment]
> What are your thoughts on Nami having a `getAvailableUTXOs()` method? Just wondering because I could definitely see other dApps running into this same problem.

Unfortunately no API exists yet to look into the mempool. I can't really know which UTxOs are in pending state. If dApps decide to submit transactions not via Nami, there is no way to find out which UTxOs were just spent.

If you want to allow the user to make more transactions, you have to handle that on your side for now. The resulting UTxO that can be spend is the tx hash with the output index of the change output.

**Comment by BlakeBrown** [comment]
Gotcha 😄 Will close this issue. 

Right now we're recommending users to spread out their NFTs over multiple Nami wallets, but it would really nice if Nami didn't gather so many NFTs into a single UTXO. Not only does this cause contention issues when listing multiple assets, but it also quickly hits the CPU + memory limits we set.

**Comment by alessandrokonrad** [comment]
> but it would really nice if Nami didn't gather so many NFTs into a single UTXO

The distribution of the UTxOs depends on the user. If a user receives 5 different NFTs in 5 transactions, there will be 5 UTxOs each with 1 NFT. This has nothing to do with Nami. You can pick as many UTxOs as you want as input, there is no contention then.

**Comment by BlakeBrown** [comment]
Got it, I apologize for assuming it was Nami that was coalescing the UTXO's. 

I did some more digging, and it appears it's actually Yoroi/Daedalus that are causing the issue as they only allow for a bulk send of assets. 

<img src="https://user-images.githubusercontent.com/6283620/145688595-f47c0c1b-3896-4ad2-9168-791e29204068.jpg" width="250px"/>

Unrelated to Nami, but might be interesting to you if you're curious about problems we're running into - this causes issues with `cardano-serialization-lib` as we have to set ExUnits for the redeemer in advance without zero knowledge of how big the transaction will be. The transactions often end up failing for these users since they are including 50+ NFT's in a single txn. The best thing we can do right now is recommend users split their assets across multiple Nami wallets, which they assume is a limitation of Nami, but is actually a limitation of the `cardano-serialization-lib`. When v10 comes out and we can calculate the correct datum hash, we'll build txns with the CLI instead before signing them over on Nami which will allow us to calculate ExUnits in advance eliminating this problem.

**Comment by rumourscape** [comment]
Hey @BlakeBrown, I am curious to know how you guys at jpg,store handled this problem. Specifically, how do you ensure that you are not re-using a UTxO from a pending tx. I would really appreciate your insight.

**Comment by BlakeBrown** [comment]
@rumourscape when a user lists something on JPG Store, we split the output into a bunch of different UTxO's so that if they then try to buy another item there are usually more UTxO's available to use.

I can't remember if we also track spent UTxO's, or if wallets are now doing that.
