### ISSUE TITLE
Testnet UI

### ISSUE THREAD

**Issue by psychomb** [Berry-Pool/nami-wallet#12]
A UI detail may be: Testnet version rightly reports tADA as a balance but still displays USD/EUR equivalent value. It probably should not - Hoping to avoid mistakes while switching between different wallets/machine/browsers.

Anyway, congrats on this nice piece of software !

**Comment by alessandrokonrad** [comment]
That's a good point, but I like to keep it in. The reason for that is, that the price is a good reference for simulating "real" transactions on the testnet.

**Comment by psychomb** [comment]
Haven't thought about that indeed ! It's up to me not to live "dangerously" then :)
