### ISSUE TITLE
SignData page doesn't show external application data

### ISSUE THREAD

**Issue by MattHalloran** [Berry-Pool/nami-wallet#122]
I'm creating an application that requests a signed message from Nami as part of the authentication process (because there is off-chain user data). To let the user know what the sign data request is for, the payload includes a description in its external application data. If the SignData page could display this in a separate box, then the user wouldn't have to find the message inbetween a bunch of random symbols.

Here is what I mean:
![Screen Shot 2021-12-06 at 9 31 46 AM](https://user-images.githubusercontent.com/26010639/144864938-5f7b5352-53e4-4635-847d-8f48a640ba68.png)

If it helps, this is how the description was set:
```
// Combine headers and payload into a COSESignBuilder
let builder = MessageSigning.COSESignBuilder.new(headers, payload, false);
// Add description to builder
builder.set_external_aad(new TextEncoder().encode(description));
```

**Comment by alessandrokonrad** [comment]
Nami only expects a payload in hex format.

**Comment by MattHalloran** [comment]
@alessandrokonrad I sent the payload in hex format. Maybe I did it wrong, but from a brief inspection of Nami's code, it looks like there is no attempt to pull a description from the payload. The process for creating and parsing the payload seems to be based off of [CIP-0008](https://github.com/cardano-foundation/CIPs/blob/master/CIP-0008/README.md#signing-and-verification-target-format), which specifies an external_aad field that: 

> allows an application to ask the user to sign some extra data but NOT put it inside the COSE structure

I think it would be useful to use this field to set human-readable descriptions. The current implementation makes applications that require the authentication handshake I used ([described here](https://cardano.stackexchange.com/a/4814/965)) look a little unprofessional.

**Comment by alessandrokonrad** [comment]
Nami really just expects a hex payload there. It's a simplified version and CIP-0008 is part of Nami and handles all the logic and returns you the COSESign1 structure.

**Comment by MattHalloran** [comment]
@alessandrokonrad So there shouldn't be a need for the hex payload to be a SigStructure? It can just be a string with a nonce instead, and it'll still be secure? When I try this with the code taken from [MessageSigning.md](https://github.com/Berry-Pool/nami-wallet/blob/main/MessageSigning.md), it throws an error in verifyAddress.
