### ISSUE TITLE
Incorrect balances shown in wallet

### ISSUE THREAD

**Issue by dshiell** [Berry-Pool/nami-wallet#130]
Hi, I recently started experimenting with Nami wallet + Sundaeswap testnet and noticed something strange. When I used the Sundaeswap faucet to fund my wallet the amounts shown are all multiplied by a million. It seems likely be a UI issue? since the Sundaeswap portfolio interface shows the expected amounts. I am using Brave Version 1.32.115 Chromium: 96.0.4664.93 (Official Build) (64-bit) on Windows 10 and Nami Wallet v2.3.2. Thanks!

![Screenshot 2021-12-08 155515](https://user-images.githubusercontent.com/1907458/145310165-4ab01002-8668-4a7c-9e66-bf87133f3c5a.png)

![Screenshot 2021-12-08 160008](https://user-images.githubusercontent.com/1907458/145310295-7140b4dd-5a9b-4b9f-8933-772a8c5da930.png)

**Comment by pascallapointe** [comment]
Hi, thanks for letting us know.
Looks like the assets on sundae swap can be divided in fraction.
Like with ADA, where 1000000 Lovelace is equivalent to 1 ADA.
Nami actually don't know about the number of decimals the asset should have, so it simply display the raw value.

I need to check more in depth to see how we handle that on our side, and if SundaeSwap minted theses coins with any metadata specifying the number of decimals.

**Comment by alessandrokonrad** [comment]
They haven't registered any metadata for these tokens, so no decimals. They are just dislplaying it with decimals on their website.

**Comment by dshiell** [comment]
Ah I see. So is this just an issue with metadata information? Should this issue be closed?
