### ISSUE TITLE
Signing transaction removes datums (and other script related data)

### ISSUE THREAD

**Issue by gege251** [Berry-Pool/nami-wallet#131]
I've been working on the integration of nami-wallet with smart contracts, but I found out that signTx removes the datum, redeemer etc. from the witnessSet, which results in an invalid tx, or a valid tx without embedded datum.
I already started doing some work on the issue, but there seem to be other problems which need to be solved.

**Comment by alessandrokonrad** [comment]
Nami only returns you its own witnesses it made, this is on purpose and not a bug. You have to merge all witnesses together with your dApp.

**Comment by gege251** [comment]
Thanks. Could we then add a comment about this for the `signTx` jsdoc? I think many people would fall into this trap.
