### ISSUE TITLE
loading for ever

### ISSUE THREAD

**Issue by lisandro-iraguen** [Berry-Pool/nami-wallet#133]
it looks like it doesn't work for me
![image](https://user-images.githubusercontent.com/70443444/145653475-65a3a753-acb6-4010-9288-c46dba343d81.png)

on
![image](https://user-images.githubusercontent.com/70443444/145653505-7b5859f9-1f29-47b1-9014-70eece73a851.png)
on windows 10

**Comment by pascallapointe** [comment]
Hi, it looks like something went bad during the update process, the storage could be corrupt.

First try to completely close the browser and reopen it. If the extension still broken, you'll have to uninstall/reinstall it and then reimport your 24 words seed phrase.

**Comment by lisandro-iraguen** [comment]
it works, thanks
