### ISSUE TITLE
Default native asset image does not contain the first letter for some assets (Bug?)

### ISSUE THREAD

**Issue by honungsburk** [Berry-Pool/nami-wallet#136]
# Bug report
## Description
The problem is best explained by this image
![image](https://user-images.githubusercontent.com/21693578/145706663-6502e55b-54fb-42cb-bb1d-1a798ede1301.png)

as seen, "FrankCoin" has F displayed in its default image but "Franks" does not have an 'F'. As a user I expect it to always show the first letter.

## Debug Info
"FrankCoin" was created using the CLI while "Franks" used the @emurgo/cardano-serialization-lib-browser library.
The cause is probably because I used two different methods of hex encoding the strings

### Hex encodings
**FrankCoin**: "4672616E6B436F696E"
**Franks**: "004600720061006e006b0073"

### Methods
**FrankCoin**: [I used this onlineconverter](https://www.convertstring.com/EncodeDecode/HexEncode)
**Franks**: 
```typescript
function hexEncode(s: string): string{
  var hex, i;
  var result = "";
  for (i=0; i<s.length; i++) {
      hex = s.charCodeAt(i).toString(16);
      result += ("000"+hex).slice(-4);
  }

  return result
}

  const hexString = hexEncode("Franks")
  const assetName: Uint8Array = Uint8Array.from(Buffer.from(hexString, 'hex'));
  txBuilder.add_mint_asset_and_output_min_required_coin(
    pubKeyScript, 
    wasm.AssetName.new(assetName), 
    wasm.Int.new_i32(mintData.amount),
    userAddress,
    );
```

**Comment by alessandrokonrad** [comment]
Yeah it should the first letter actually🤔. Could you let me know the assetId/fingerprint of that token?

**Comment by honungsburk** [comment]
**FrankCoin**
policyid: bd7f7e20e9d43ffb11fdd3c08f32fc31292f8deb72696e5fe003c832
fingerprint: asset18mueg6t39cw0a2lj6cxsa96308kcepqqnjmfxm

**Franks**
policyid: 425754c55895d05430ea30c57a6bc2f7f180756f598a5bb0221c3357
fingerprint: asset1qcjvmv97ry857ruxtpx7nu793qh6gg7nqglzh8

Note that these assets are issued on the **testnet**

**Comment by alessandrokonrad** [comment]
So it looks like the hex function may not be fully correct. Cardanoscan can also not display the token name, but just shows a string of hex digits: https://testnet.cardanoscan.io/token/0624cdb0be190f4f0f86584de9f3c5882fa423d3
 I would recommend you to use Buffer:
```
const hexName = Buffer.from("Franks").toString("hex")
```

**Comment by honungsburk** [comment]
Good, but before I close this issue: Are you aware of any restrictions on what characters can be a part of an asset name? Is it only alphanumeric? I believe the docs I say the only restriction is that it is no more than 32 bytes.

**Comment by alessandrokonrad** [comment]
It can be any character and yes 32 charactes is maximum.

**Comment by honungsburk** [comment]
Thank you!
