### ISSUE TITLE
FR: Simple Transaction Endpoint in API

### ISSUE THREAD

**Issue by Crypto2099** [Berry-Pool/nami-wallet#14]
Create an API endpoint that will allow a website (such as a token drop or merchant interaction) to simply send parameters for a transaction (i.e. send me 15 Ada to this address) rather than requiring merchants to build out the entire transactional logic on behalf of the user's wallet.

The current low-level implementation seems rife with the possibility for errors on behalf of the merchant/vendor and could also lead to scams and abuse. The wallet already has native token selection and transaction compilation logic embedded so much better for a vendor to simply request funds and provide a payment address and leave the logic to the wallet.

In considering the current CNFT space, perhaps this could also specify one or more tokens that should be provided (i.e. 500 spacecoins, 1 Spacebudz, etc) as part of some gamification, escrow, etc.

**Comment by alessandrokonrad** [comment]
I would prefer building an external libary around, which also includes a simple send function.
I follow this CIP: https://github.com/cardano-foundation/CIPs/pull/88
I think it's best to keep the injected API as small and flexible as possible.

**Comment by FrancoAra** [comment]
Hey @alessandrokonrad, I am starting to integrate with Nami, thank you very much for your great work. It would be an awesome developer experience if you add a "high level api" to interact with the injected api, you can still leave the "low level api", but we are all probably reinventing the wheal for things like making simple transactions or requesting delegation. Plus going through the serialization lib learning curve and other low level cardano details is a heavy

**Comment by FrancoAra** [comment]
or at least can we get an example of making a simple transfer transaction and requesting delegation to a pool? T_T haha
