### ISSUE TITLE
"HW not supported" when connecting Nami-ledger to CNFT

### ISSUE THREAD

**Issue by TheCaptRay** [Berry-Pool/nami-wallet#141]
Can someone tell me why this is happening? Are we not able to buy/sell NFTs on marketplace with Legder (Nami)? or is it just an issue with CNFT?

"HW not supported" when connecting Nami-ledger to CNFT.

**Comment by alessandrokonrad** [comment]
HWs can't interact with smart contracts yet, this functionality may come soon, but that is not in our hand, we have to wait for some software updates.

**Comment by TheCaptRay** [comment]
Oh okay, but why can't I add Collateral 5ADA to my wallet?
