### ISSUE TITLE
Nami Wallet forever loading, didn't received my Ada tokens

### ISSUE THREAD

**Issue by DanCpt86** [Berry-Pool/nami-wallet#142]
Hello,

I have installed my Nami Wallet on my Google Chrome 5 days ago,

After that I have transferred some ADA from Binance Spot Wallet to the address provided in my Receive tab, using Cardano Network.

My account Nami Wallet is Dancpt86. I haven’t received the Ada in my wallet, or maybe I received them ( Binance said the Ada left from their wallet) , but if Nami wallet is not loading it doesn’t show my assets.

Please find attached picture of how the Nami not loading looks like. 

Also below are the transactions ID from Binance

49 ada as below Transcation ID 1134cd8b50a5c3025703dca2e4bfa3214283f5cc53aa19edfed3e2dce6a82758 
12 Ada as below transaction ID 1134cd8b50a5c3025703dca2e4bfa3214283f5cc53aa19edfed3e2dce6a82758 

I really hope you can solve my issue. I don’t want to loose the Ada, I want to send more Ada in the wallet and prepare it for SundaeSwap pool.

Also I don’t want to make negative publicity to the wallet for this problem,

Please have a look and send me an answer.

Best regards 

Dan 
![Nami](https://user-images.githubusercontent.com/96284307/146507906-bc0e40e2-17db-4323-80ea-69cea6d2a09a.png)

**Comment by DanCpt86** [comment]
As an extra information the wallet is installed on Google Chrome, OS System is Windows 10 Pro. I can provide additional information if needed. Also i reseted the wallet several times already, even of Edge. Also i uninstalled the extension on Chrome several times already as well.

Thank you

**Comment by alessandrokonrad** [comment]
Hey, do you get this pending loading screen each time? Even after reinstalling Nami?
It looks like you are not able to fetch some data from the coingecko Api, maybe their API was down. Can you check if you can open up this link and get a result: `api.coingecko.com/api/v3/simple/price?ids=cardano&vs_currencies=usd`

And to check if you received your funds you can look on any explorer like cardanoscan.io. There is definitely nothing lost, because Nami is simply an interface, the errors are internally in Nami, but that is seperate from your keys.

**Comment by DanCpt86** [comment]
Helo, Thank you for your answer. I couldn't open that link and i know what is the problem, i have a gambling site blocker like Gamban and the link is blocked. But i solve now the isse, someone advised me to install Yoroi Wallet and import my Nami wallet in it, and it works, i have my ADA in Yoroi now. perfect :)

**Comment by alessandrokonrad** [comment]
> i have a gambling site blocker like Gamban and the link is blocked

Oh okay, yeah that one blocks the API from loading and so Nami can't continue with loading the rest. Okay great!
