### ISSUE TITLE
Feature improvement: Allow history tab display "minting" events with negative amounts as "burning" 

### ISSUE THREAD

**Issue by honungsburk** [Berry-Pool/nami-wallet#149]
## Motivation
As a user, it would be nice to show a minting transaction with a negative amount as "Burning". Of course, then there is the question of what to do in the case that there is both burning and minting in the same tx...

## Current
What it currently looks like in the GUI:
**Looks like I'm minting**
![image](https://user-images.githubusercontent.com/21693578/146666109-5a7bb6b2-62eb-4397-9516-278087c5184d.png)
**But I am burning**
![image](https://user-images.githubusercontent.com/21693578/146666111-853d3e8a-8171-441a-a277-3d0ca339b300.png)

## Replicate Issue
You can use https://native-asset.com/ to create your own minting/burning transactions.

**Comment by alessandrokonrad** [comment]
Hey thanks for the suggestion. This is definitely tricky, especially in the case of both minting and burning happening at the same time as you already say.
The meaning here of "Minting" should be more understood as the overall event and that something is specified in the mint field of the transaction. and not that something was necessarily forged, but could have also been burnt. We could change the icon tho, which may be misleading.
