### ISSUE TITLE
Cardano.signTX error

### ISSUE THREAD

**Issue by elRaulito** [Berry-Pool/nami-wallet#15]
Hi!
thanks a lot for this tool,
I am trying to sign some transactions but I keep getting this error "**Inputs do not conform to this spec or are otherwise invalid.**"

My api call is:
```
let transaction= {tx:"83a30081825820745084b076a17275916921ad4cadbda2ef071587fe0b2cda80e14df5a2848a83000182825839011c471b31ea0b04c652bd8f76b239aea5f57139bdc5a2b28ab1e69175fd3a6bfce30d7744ac55e9cf9146d8a2a04ec7fb2ce2ee69862606531a000c917b825839010d50033b5cfc6177d1bf3fdfc958fc0112b4ec3ba12960df29cebfe39500d456024a38c1658ff57ba22f2f91612aad725ad26a1d2daf00f31a001e8480021a0002b0c59ffff6"};
console.log(transaction)
const signedTx=await cardano.signTx(transaction);
```

**Comment by alessandrokonrad** [comment]
Hey!
`cardano.signTx` takes a raw cbor string as argument. Did you create the tx with the cardano-cli?

**Comment by elRaulito** [comment]
Yes! I built the transaction and then used the 'cborHex' argument

**Comment by alessandrokonrad** [comment]
For some reason the cli creates an empty witness set in form of an array, although in the ledger specs it's a map. You can make a small transformation from an array to a map with this function:
```
const cbor = require("cbor");

const convertCbor = (txRaw) => {
  const decoded = cbor.decode(txRaw);
  decoded.splice(1, 0, new Map());
  return cbor.encode(decoded);
};
```
The result you can then use as argument for `cardano.signTx`
The cbor library you can get here: https://www.npmjs.com/package/cbor

**Comment by elRaulito** [comment]
Ok almost there, I have been able to get a uint8 array, here the encoded form `'84a30081825820745084b076a17275916921ad4cadbda2ef071587fe0b2cda80e14df5a2848a83000182825839011c471b31ea0b04c652bd8f76b239aea5f57139bdc5a2b28ab1e69175fd3a6bfce30d7744ac55e9cf9146d8a2a04ec7fb2ce2ee69862606531a000c917b825839010d50033b5cfc6177d1bf3fdfc958fc0112b4ec3ba12960df29cebfe39500d456024a38c1658ff57ba22f2f91612aad725ad26a1d2daf00f31a001e8480021a0002b0c5a080f6'`


Unfortunately the error keeps being the same 
`const signedTx=await cardano.signTx(tx: uint8Array);`

**Comment by alessandrokonrad** [comment]
You simply take the raw cbor string from the cli and pass it in the `convertCbor` function. The return value you then put in the `cardano.signTx` function. That's all you need to do.

**Comment by elRaulito** [comment]
Thanks a lot @alessandrokonrad, as you told me the working code is:

``` const cbor = require("cbor");

const convertCbor = (txRaw) => {
  const decoded = cbor.decode(txRaw);
  decoded.splice(1, 1, new Map());
  return Buffer.from(cbor.encode(decoded), "hex").toString("hex");
};
