### ISSUE TITLE
ADA & NFTs not showing up when entering seed phrase

### ISSUE THREAD

**Issue by HoopToIt** [Berry-Pool/nami-wallet#157]
Hi. I've entered the seed phrase of my existing wallet that contains ADA and NFTs. In Nami, it says that there's no NFTs or ADA. The message says "We have detected that the current wallet seed has been used with another wallet." 

I don't want to have to transfer the entire wallet over to a new Nami wallet (that will have a massive fee attached), so I'm wondering if there's another way to get my wallet working on Nami? I want to start using smart contract sites for my NFTs. Thanks.

**Comment by pascallapointe** [comment]
You can create a secondary account and transfer just enough ADA on the secondary account to interact with smart contract, otherwise, the 2 options described in the warning message are the only choices you have to get Nami to properly display your assets.

**Comment by HoopToIt** [comment]
Thanks for your answer - the main issue is that I have a lot of NFTs in my main wallet that I want to sell. Is there no way to do this  except to send them to a newly created Nami wallet?
