### ISSUE TITLE
Collateral keeps getting unset 

### ISSUE THREAD

**Issue by adirss** [Berry-Pool/nami-wallet#160]
My collateral keeps getting unset after every transaction, sometimes the collateral even doesnt work on cnft.io
my balance different is always -5 in nami sometimes even -10 , but in other wallet service is just normal.
i ask the community but it seems like only i expirience this.
i dont know what might happen when i have active listing on cnft.io while my collateral having an issue

![image](https://user-images.githubusercontent.com/43319835/147065042-07409ce4-feae-432e-9bb4-31a691ac378a.png)
this is what it looks like

**Comment by alessandrokonrad** [comment]
Hey, can you let me know what Nami version you are on?

**Comment by adirss** [comment]
im using 3.0.0 , but i think  the first time it happen before the latest update. i also just re download the extention and it literally happen again today. for extra info im also using ccvault on this one wallet

**Comment by adirss** [comment]
that make sense, however it also gets unset even when trx come in. i guess i should separate them
