### ISSUE TITLE
Not all assets shown

### ISSUE THREAD

**Issue by BRudDraw** [Berry-Pool/nami-wallet#164]
I have a wallet with a large number of assets inside, when I navigate to pool.pm I am able to see all of the tokens and NFT's inside of my wallet.  However when using Nami and scrolling through the collectibles, half are not shown and unable to be listed on marketplaces such as CNFT as an error message on the marketplace states that the asset is not in the wallet.  How would I go about fixing this issue?
![Screenshot 2021-12-23 140647](https://user-images.githubusercontent.com/69051320/147287476-ec702c64-e261-410f-837b-b82ab3ea35fe.png)
![Screenshot 2021-12-23 140721](https://user-images.githubusercontent.com/69051320/147287477-a86de264-140a-458a-9967-1ff99170c0be.png)

**Comment by pascallapointe** [comment]
Hi, can you tell us if the number of token under the asset tab + the number of collectible match the 324 number displayed on pool.pm?

**Comment by BRudDraw** [comment]
We can close this out, I figured out the issue.  It was due to not selecting a single address option for Nami using CCVault.  After which and sending a transaction everything was rectified.

Thank you for reaching out
________________________________
