### ISSUE TITLE
Could not add collateral with connected Ledger wallet 

### ISSUE THREAD

**Issue by kochfoto** [Berry-Pool/nami-wallet#166]
I have a Ledger wallet loaded in my Nami but when i try to add collateral, the confirm button is grayed out.
![7273E288-378E-4EC1-BEC5-AFAA4EB5F80A](https://user-images.githubusercontent.com/976825/147358055-f29fbff2-7fd7-4fd2-b5e1-812b9596b29a.jpeg)

**Comment by pascallapointe** [comment]
Cardano Smart contract isn't supported by ledger yet, we are waiting for them to add the support. The button is grayed out because you can't use the ledger to interact with smart contract at the moment.
The button will be enabled as soon as we add support for it.
