### ISSUE TITLE
Nami wallet lost or missing NFt digital pic

### ISSUE THREAD

**Issue by Aceguwa69** [Berry-Pool/nami-wallet#168]
I bought 3 nft from CNFT market place. Then It went to my nami wallet so it was ok. Then today I log back in it was 1 is missing I dont know what happen but I submitted a complain to  CNFT to have a ticket but no Acknowledgement my submission.Even a rob return acknowledgement to my report. And Nami have no help link either.

**Comment by pascallapointe** [comment]
- Check your wallet address account using pool.pm to make sure that you are not just facing a display/sync issue.
- Make sure that the NFT is neither under the asset tab, nor under the collectible tab.
- Go in "send" screen, click on the "asset" button and make sure that the asset isn't displayed there either. (The send page load a fresh copy of your assets)

If you can't find the assets, you will need to dig your transaction history to find out what happened. You can check on Nami history tab if the NFT was ever received, and if it as been sent away later on. You can also check your wallet history on cardanoscan as a second way to verify the data.

**Comment by Aceguwa69** [comment]
THANK YOU IT IS NOW RESOLVED. ALL IS NOW FINE AND MORE POWER CNFT.IO
