### ISSUE TITLE
signTx() thorws "Invalid" in 3.0.0.1 for transactions which worked in 3.0.0.0

### ISSUE THREAD

**Issue by Sbcdn** [Berry-Pool/nami-wallet#170]
Hello, 

Since 3.0.0.1 the signTx() function does throw  "code: -1, info: 'Inputs do not conform to this spec or are otherwise invalid.'"
On transaction which work in 3.0.0.0 and are still working e.g. in ccVault. 

I found you added check for networkId in the latest version and I believe it has something to do with that, but I am not able to find out what exactly causes the crash. 
( https://github.com/Berry-Pool/nami-wallet/commit/db72c4aa9cddc506ab9eff2782d7e20b45665e66 )

Until 3.0.0.1 we did not had issues with the signature process and our code did not changed. 
We build our transactions with rust here is an example transaction which fails:

```84a60081825820f9044594f206341ec3b187b3be470fc20c329ab873741de38898faea7f60371503018283581d70019c2c0c68c283bbc2e52aebae4cfe94ccfe1a911c457a3007237682821a001e8480a1581cdd78158839fae805523ba4c0aa5cd3d7fa4adb43f7ae8c7ebf1d5dd9a1564172746966637454657374546f6b656e3030303139340158203985850c2f4d147006ab017f428b8b4d418a6e3bf049df5e4e9310c401918106825839005c0ae5846b98ee351c32f701d53f269054d4f1bb0550a7255cad812e54f8aae0330f24a2c4ee78ebd97642d0e4c3cb6dd6a569e9d5132030821a19df0d1ea1581cdd78158839fae805523ba4c0aa5cd3d7fa4adb43f7ae8c7ebf1d5dd9a4564172746966637454657374546f6b656e30303031393601564172746966637454657374546f6b656e30303031393701564172746966637454657374546f6b656e30303032303201564172746966637454657374546f6b656e30303032373301021a0002d79d031a02d0c17b075820d64beeec17e35334fae0d94f4f3dcc0e132206eb536e0ad43ec75e3971486ed70f00a0f5a119013887483435303030303030581c5c0ae5846b98ee351c32f701d53f269054d4f1bb0550a7255cad812e581cdd78158839fae805523ba4c0aa5cd3d7fa4adb43f7ae8c7ebf1d5dd9564172746966637454657374546f6b656e303030313934581f616464725f7374616b6531326e75323463706e70756a323933387730723461581f6a616a7a36726a76386a6d6436366a6b6e3677347a7673727137723563336d52617274696663742d636c692d76312e302e30```
Decoded:
```
[{0: [[h'F9044594F206341EC3B187B3BE470FC20C329AB873741DE38898FAEA7F603715', 3]], 1: [[h'70019C2C0C68C283BBC2E52AEBAE4CFE94CCFE1A911C457A3007237682', [2000000, {h'DD78158839FAE805523BA4C0AA5CD3D7FA4ADB43F7AE8C7EBF1D5DD9': {h'4172746966637454657374546F6B656E303030313934': 1}}], h'3985850C2F4D147006AB017F428B8B4D418A6E3BF049DF5E4E9310C401918106'], [h'005C0AE5846B98EE351C32F701D53F269054D4F1BB0550A7255CAD812E54F8AAE0330F24A2C4EE78EBD97642D0E4C3CB6DD6A569E9D5132030', [434048286, {h'DD78158839FAE805523BA4C0AA5CD3D7FA4ADB43F7AE8C7EBF1D5DD9': {h'4172746966637454657374546F6B656E303030313936': 1, h'4172746966637454657374546F6B656E303030313937': 1, h'4172746966637454657374546F6B656E303030323032': 1, h'4172746966637454657374546F6B656E303030323733': 1}}]]], 2: 186269, 3: 47235451, 7: h'D64BEEEC17E35334FAE0D94F4F3DCC0E132206EB536E0AD43EC75E3971486ED7', 15: 0}, {}, true, {312: [h'3435303030303030', h'5C0AE5846B98EE351C32F701D53F269054D4F1BB0550A7255CAD812E', h'DD78158839FAE805523BA4C0AA5CD3D7FA4ADB43F7AE8C7EBF1D5DD9', h'4172746966637454657374546F6B656E303030313934', h'616464725F7374616B6531326E75323463706E70756A323933387730723461', h'6A616A7A36726A76386A6D6436366A6B6E3677347A7673727137723563336D', h'617274696663742D636C692D76312E302E30']}]
```

The networkId is correctly set as you can see in the decoded cbor so I do not really understand why it fails. 
Would appreciate any hint about what Nami expects different now to succeed signature process again. 

Thank you

**Comment by alessandrokonrad** [comment]
Thanks! Indeed there is a little bug. Calling just `txBody.network_id()` returns an object and not a number as I have expected, which is the case tho when you get the network id from an output address.
