### ISSUE TITLE
Can't set collateral on ledger.  Confirm screen wont turn on. I tried resetting everything already.

### ISSUE THREAD

**Issue by kongfuhero1** [Berry-Pool/nami-wallet#173]
<img width="317" alt="Screen Shot 2021-12-29 at 8 30 22 PM" src="https://user-images.githubusercontent.com/96856276/147721897-0359ec18-6621-4460-8a85-d9c214032745.png">

**Comment by alessandrokonrad** [comment]
HWs do not support smart contracts yet, so this option is disabled.

**Comment by katakombi** [comment]
is this a limitation in the cardano ledger app or does it just need to get implemented in nami?

**Comment by alessandrokonrad** [comment]
It's a limitation in the ledger app. It's in the works as far as I know, but I don't know when it will be shipped exactly.
