### ISSUE TITLE
Receive address issue

### ISSUE THREAD

**Issue by WayOfJ** [Berry-Pool/nami-wallet#174]
After clicking on the receive address to copy, the pasted address is different from the copied address. I sent some ada to test out and have not gotten it since, would like to know the issue, thanks!

**Comment by WayOfJ** [comment]
![ss1](https://user-images.githubusercontent.com/92166923/147733560-601859ce-7429-411c-a1ae-542523bc527f.png)

**Comment by WayOfJ** [comment]
pool.pm/addr1q988hx9r9dfxvaqj4gcdwnyqvhj2uxqhxhljkjmmam598k6w0wv2x26jve6p923s6axgqe0y4cvpwd0l9d9hhmhg20dsacvq6y

**Comment by MarcelKlammer** [comment]
Did you find the cause of this? It seems to be a malware of some kind.
Did you find any other wallet changing the address for you?
