### ISSUE TITLE
How to Redelegate from Meld to other ISPOs.

### ISSUE THREAD

**Issue by callen5313** [Berry-Pool/nami-wallet#177]
Hello. I need to redelegate from a closed pool, Meld, into a new pool. Can you tell me how to do that?
Also, how many pools can I delegate to simultaneously?

**Comment by pascallapointe** [comment]
You just have to select a new pool on pool.pm and delegate to it. Nothing special to do. You don't need to undelegate to change delegation.

To delegate to different pools you need to create multiples sub accounts. Each account can be delegated to a different pool.
