### ISSUE TITLE
Sent CNFT through Nami wallet on cnft.io and now it is gone but didn't get any credit

### ISSUE THREAD

**Issue by spear138** [Berry-Pool/nami-wallet#178]
I sent a Cardano Crocs Club CNFT and it never got there. Super bummed... Can you help me?

Transaction hash 4d40ec2f94ced8adb0c002234ee75025484a6298b3142c41e57a4ff7906d7201

Time: 
12/30/2021 6:48:02 AM PST

**Comment by alessandrokonrad** [comment]
This looks like an issue with CNFT.io. Please ask them what has happened.
