### ISSUE TITLE
My second computer does not have my second wallet created

### ISSUE THREAD

**Issue by financeguy212** [Berry-Pool/nami-wallet#182]
How do I get the additional wallet on my second computer? When I created the Wallet2 on my first computer, it did not require new seed phrase. It just generated a different wallet address. How can I add that wallet2 with NFT's within, to my second computer? There is no import function. I thought it would sync with Chrome browser automatically but apparently has not.

Thoughts?

**Comment by alessandrokonrad** [comment]
You mean you created a new account in Nami? All accounts you created are derived from the same seed phrase in a sequential order. So whenever you reimport the seed phrase in Nami, you derive exactly the same accounts if you create new accounts.

**Comment by bawse** [comment]
@alessandrokonrad I'm facing the same issue here - I reimported the seed phrase in Nami on another device, but it didn't pull any of the new sub-accounts I had created originally. On reimport, my wallet was completely empty. The seed phrase is correct too.

**Comment by financeguy212** [comment]
I figured it out. Just needed to choose New Wallet then call it the same name as the other one and everything was there. No need to re-input any seed phrases. TY

**Comment by alessandrokonrad** [comment]
> Just needed to choose New Wallet then call it the same name as the other one and everything was there

The name can be completely different, you always derive the same sub accounts.
