### ISSUE TITLE
ADA Deposit Not Syncing - Nami

### ISSUE THREAD

**Issue by jag1423** [Berry-Pool/nami-wallet#185]
Hello,

I just recently created a Nami wallet.

I just sent ADA from my Kraken acct to Nami. 

Kraken shows that the transaction was a success and funds were taken from my acct. 

Its been roughly 2 hours and the funds have yet to be shown on my Nami wallet though. 

Can someone please help me with this. I'm so confused as to what has transpired.

Thank you!
[IMG_7723.jpg.pdf](https://github.com/Berry-Pool/nami-wallet/files/7809771/IMG_7723.jpg.pdf)

**Comment by alessandrokonrad** [comment]
Hey, can you check if you see something under the transaction history in Nami?

**Comment by jag1423** [comment]
> Hey, can you check if you see something under the transaction history in Nami?

Hi, 

There is nothing under the transaction history. The Nami wallet looks simple to use, i don't understand what happen

**Comment by alessandrokonrad** [comment]
Did Kraken give you a transaction id, which you can look up on a cardano explorer?

**Comment by jag1423** [comment]
Hi,

Thank you so much for your assistance. after reviewing the transaction on Cardano explorer, i realized that i accidentally sent the funds to a different wallet of mind.  SMH.

Thanks again for all you help.. :)
