### ISSUE TITLE
Showing incorrect balance with compatibility hint

### ISSUE THREAD

**Issue by yellowyunicorn** [Berry-Pool/nami-wallet#188]
Hello,
I connected by Nami Wallet to CCVault and got an hint, I deleted the Nami wallet off of CCVault but the issues still persisted. I am confused at the "Internal transfer of your complete balance from your usual wallet to your Nami Wallet receive address." 

It is showing a balance that is 30 ADAs off.

**Comment by alessandrokonrad** [comment]
Nami only tracks a single address, but is aware of all addresses that are tied to your stake key. CCVault uses multiple addresses. 
> It is showing a balance that is 30 ADAs off.

You mean in the compatibility hint or on the main screen in Nami?

**Comment by qtinterval** [comment]
How do you fix it then? Would he send himself exactly 30 ADA to the Nami receive address to remove the compatibility hint?

**Comment by yellowyunicorn** [comment]
Found out I had to change it in ccvault setting to single address and send everything to the receive address!

**Comment by qtinterval** [comment]
Thank you! So what I did for anyone reading this in the ~ F U T U R E ~  was set CCVault to single address in Settings, and then sent myself the total 100% amount inside my Nami wallet (from CCVault) to my original Nami wallet address. That fixed it, removing the Compatibility Hint warning in Nami.

**Comment by KJamesBA** [comment]
Will this work by sending all assets and tokens? i cant just send all ada with out getting an error
