### ISSUE TITLE
Cant send collectibles to sub account. Transaction Not Possible.

### ISSUE THREAD

**Issue by Winstonman78** [Berry-Pool/nami-wallet#194]
I keep getting "transaction not possible" when trying to send a collectible to sub account.   Tried selecting the sub account and also tried pasting receiving address of sub account.   I can send ADA but cannot send any collectibles.   i have collateral and I have plenty of ADA
![image](https://user-images.githubusercontent.com/70665321/148617903-17487f78-d48a-4ad0-84be-f2f3ff8da30e.png)

**Comment by alessandrokonrad** [comment]
Could you try to increase the auto inserted ADA amount a little bit? Maybe something like `1.42`. Let me know if that works.

**Comment by Winstonman78** [comment]
That worked increasing it to 1.5.  Thank you so much. I didnt think about
trying that.
