### ISSUE TITLE
how to add datum?

### ISSUE THREAD

**Issue by mailtodanish** [Berry-Pool/nami-wallet#195]
When we are generating a transaction we are sending some assets. Like tADA or other. 

When we send the transaction you can add optional parameters like metadata and/or datum.

datum is used by smart contract since it's the only data that smart contract can see.

![Untitled](https://user-images.githubusercontent.com/7193460/148647601-90f80124-fe56-47ef-aa61-b5418c0abb98.png)

**Comment by alessandrokonrad** [comment]
You build the whole transaction yourself and let nami sign it via the `window.cardano.signTx` endpoint

**Comment by mailtodanish** [comment]
Datum is a data that is consumed by smart contract when 'locking' event happens...I am not able to find how to implement this.
'locking' happens when we  send a transaction to the smart contract address.
