### ISSUE TITLE
how to achieve this using nami-wallet-api?

### ISSUE THREAD

**Issue by mailtodanish** [Berry-Pool/nami-wallet#200]
We generate datum script using below :

cardano-cli transaction hash-script-data --script-data-file ${datum_name}.datum

It generates the datum script. once we have datum we need to incluide it into transaction 
that is generated on cli again

 cardano-cli transaction build \
                --alonzo-era \
                --tx-in ${utxoin} \
                --tx-out ${SCRIPT_ADDR}+${LOCK_AMNT} \
                --tx-out-datum-hash ${hashes[0]} \
                --metadata-json-file metadata.json \
				
Please let me know how to do above using nami-wallet-api?

**Comment by alessandrokonrad** [comment]
I don't know what you mean with nami-wallet-api. Nami takes a raw transaction in cbor and can sign that. As I told you, you can use the `window.cardano.signTx` endpoint to give it the raw transaction.

**Comment by mailtodanish** [comment]
Hi @alessandrokonrad , I am very new in cordano . I want to implement below url (datums) . we have React applictaion and already connected with nami wallet and able to do transaction. 

https://docs.cardano.org/plutus/datums-redeemers

Today, I saw your interview  with hoskinson on youtube  and come to know that  @alessandrokonrad  is creator of nami-wallet.

**Comment by mailtodanish** [comment]
**Thanks it is resolved.** I have used below code (set_data_hash).

let outputs = this.S.TransactionOutputs.new();

const datums = this.S.PlutusList.new();
const datum = this.S.PlutusData.new_constr_plutus_data(
this.S.ConstrPlutusData.new(
				this.S.Int.new_i32(1),
				this.S.PlutusList.new()
				)
);
datums.add(datum);

let t = this.S.TransactionOutput.new(
          this.S.Address.from_bech32(ReceiveAddress),
          outputValue
        );
t.**set_data_hash**(this.S.hash_plutus_data(datum));
outputs.add(t);
