### ISSUE TITLE
Incorrect error msg when submitting a transaction

### ISSUE THREAD

**Issue by honungsburk** [Berry-Pool/nami-wallet#208]
Nami returns the error
![image](https://user-images.githubusercontent.com/21693578/149488839-40b32745-6b09-411b-afa4-3465ad5af81e.png)

when you use `submitTx()` and the tx is incorrect (example: assets in doesn't match assets out).

**Comment by alessandrokonrad** [comment]
Interesting. I'm actually not sure how `code` could be ever something else than a number.
The error codes are defined here: https://github.com/Berry-Pool/nami-wallet/blob/797d2a695081ba1a90b7be3b37c18d555a310758/src/config/config.js#L162-L176

And txSubmit is here: https://github.com/Berry-Pool/nami-wallet/blob/797d2a695081ba1a90b7be3b37c18d555a310758/src/api/extension/index.js#L962-L977

**Comment by alessandrokonrad** [comment]
![Screenshot 2022-01-14 at 11 41 43](https://user-images.githubusercontent.com/35738310/149502685-8925a8bf-2d48-41e3-b61e-b357c791c0b6.png)

The error code should look something like this, with an additional message property showing you what's wrong with the tx

**Comment by honungsburk** [comment]
Sorry, my bad. Found the culprit in my own code
