### ISSUE TITLE
CIP-0030 compatible injected API

### ISSUE THREAD

**Issue by dauta-toast** [Berry-Pool/nami-wallet#209]
Hello 👋 

First off, thank you for building this wallet and being so responsive with issues! 
I'm curious about the plan on making the injected API CIP30 compatible. I see that there is a commented out code, that should basically get it there. Is there something that's stopping the change? 
I would be willing to assist, if it's a matter of lacking time. 

I mainly ask, because with Yoroi already rolling out the dapp connector in the nightly build, we have to have two conflicting implementations of the Nami and Yoroi APIs. 
Thanks in advance!

**Comment by alessandrokonrad** [comment]
Hey! The reason why I haven't moved yet to CIP-0030 is that Nami has event functionality and some other endpoints, which CIP-0030 does not have yet. There are ongoing discussions, but the process is really slow. However it seems like there is going to be an experimental section introduced in the CIP, so every wallet has a little bit of freedom to use some custom endpoints. I see CCVault already using it, so I'm working on it maybe today or tomorrow.

**Comment by dauta-toast** [comment]
Amazing! Thanks for the quick reply. Yeah, I saw ccvault implemented `getCollateral` as an experimental function. Looking forward to having standardized dapp connector.
I can close the issue. Or would you prefer to keep it open to track it? 
Thanks again!

**Comment by dauta-toast** [comment]
This has been resolved, so I'll close the issue. Thanks again!
