### ISSUE TITLE
Can't set my collateral and enlist my NFTs

### ISSUE THREAD

**Issue by euisjot** [Berry-Pool/nami-wallet#214]
Hello, I need your help. I want to connect my wallet to http://cnft.io after I reset it because it keep loading, whenever I try to listing my NFT it always says I need to set collateral first. I can't enlist my NFTs there too. So I tried to set collateral but it's always failed. Can you help me? And I also can't see 1 of my NFT on asset, before I reset the wallet I'm sure it still there, I already check on pool.pm too and I can see the NFT.
Here's my wallet address:
addr1q96yu5z0ngnx6mvtwg0pyr6zh7hwejjc64djp5qsre53zyw49ltkk35yaetv2a4s4lj8gm290eugx48e2ud7gl8vjrwq4pe3mk
Thankyou!

**Comment by euisjot** [comment]
Update:

I finally success to set my collateral, now the other problem. whenever I tried to enlist my smart contract listing in cnft.io, it said "invalid collateral". I should ask help from nami or cnft.io? thanks

**Comment by samyakjaipuria** [comment]
How did your collateral issue got resolved
