### ISSUE TITLE
Cant add collateral 

### ISSUE THREAD

**Issue by ahmedelakkad** [Berry-Pool/nami-wallet#216]
Can't add collateral. Transaction failed. Reset wallet 3 times and same thing.

**Comment by rafek47** [comment]
Same issue, using HW wallet Ledger Nano S

**Comment by aidansmithh** [comment]
So do you have two wallet addresses now??

**Comment by rafek47** [comment]
> 

how do you mean that?

**Comment by ahmedelakkad** [comment]
Turned out to be Cardano network congestion. Will close this issue.
