### ISSUE TITLE
Transaction failed mempool full

### ISSUE THREAD

**Issue by johnnyjordan02002** [Berry-Pool/nami-wallet#273]
Whenever I try and put in collateral so i can sell my nfts through smart contracts it says the mempool is full and to try again and it just keeps happening over and over can someone help me

**Comment by mrahmansurrey** [comment]
I'm having the same issue. Missed out on some great buys because of this, very frustrating. I better be able to transfer my ada back out atleast.

**Comment by johnnyjordan02002** [comment]
Yeah it is very frustrating im not sure what the issue is

**Comment by pascallapointe** [comment]
Hi, to set a collateral the wallet needs to do a transaction to create a small UTxO of 5 Ada.
There is actually to much activity going on and Nami backend provider mempool is saturated. A mempool is like a queue where your transaction is waiting to get pushed to the blockchain.

Read this twitter chain post to learn more on what's going on: https://twitter.com/berry_ales/status/1483936557954486272
