### ISSUE TITLE
Adding collateral. Transaction failed???

### ISSUE THREAD

**Issue by mrahmansurrey** [Berry-Pool/nami-wallet#274]
I have deposited a large amount of ADA to my Nami wallet to buy some CNFTs, however when I try to set my collateral I keep getting the following error message 'Transaction failed
Mempool full. Try again.' What do I do???

**Comment by pascallapointe** [comment]
Hi, to set a collateral the wallet needs to do a transaction to create a small UTxO of 5 Ada.
There is actually to much activity going on and Nami backend provider mempool is saturated. A mempool is like a queue where your transaction is waiting to get pushed to the blockchain.

Read this twitter chain post to learn more on what's going on: https://twitter.com/berry_ales/status/1483936557954486272
