### ISSUE TITLE
Lost ADA through Nami Chrome Extension

### ISSUE THREAD

**Issue by johnnyscotcho** [Berry-Pool/nami-wallet#298]
i have been using your chrome extension and I think i was adding collateral or delegating (im actual a little confused by both) and somehow i sent 1000 ada. Could you please help me figure this out. 1000 ada is a lot of money to me and im really hoping i did not loose it. I appreciated any help you can give me:

https://cardanoscan.io/address/addr1q98tzjd327vsvpxms3pf8hdacuj7xaz7ne0ruv37ytw08fa2j3xz9suz388z35fg7vt8wxzclyahfvakguj8n3l0sx6smzd7z8

**Comment by HeptaSean** [comment]
As far as I can see, the 1000 ADA have gone into a SundaeSwap contract. You should see an order in SundaeSwap that you can cancel to get them back. (I'm not Nami, though, but it will probably take a while, till they come to all these issues.)

**Comment by johnnyscotcho** [comment]
Thank you so much. I found the open order

**Comment by HeptaSean** [comment]
Would be nice to close the issue if all is solved, so that the Nami developers do not have so much to wade through. Thank you!

**Comment by johnnyscotcho** [comment]
hopeful i can cancel the order through SundaeSwap but issue is closed.
