### ISSUE TITLE
Making storage resilient to structure change

### ISSUE THREAD

**Issue by pascallapointe** [Berry-Pool/nami-wallet#30]
### Issue
Making storage data structure change breaks the wallet, forcing users to reinstall the extension to fix the issue.

### Current work-around
The wallet is currently using if/else condition check to adopt the proper behavior. This will quickly go out of hands, thus the current issue to find a better way.

### Some possible options

Adding a version field that test last storage version against current software version, or possibly a storageVersion field, then:

options:

- flush all storage except the user master key, tracked account and user settings choices. Since all data are fetch from an API, the wallet can rebuild the new data structure from scratch. Downside: the cache is void causing long loading time after every update.
- creating a storage migration mechanism. Upon detecting a version change, the wallet will seek for migration script to run. The migration script ensure the proper migration of one data structure to an other without any data loss. The migration number is then tracked in a migrationVersion to avoid running it again. Downside: The implementation of the mechanism and writing bug free migration is tedious.

**Comment by sublayerio** [comment]
You can implement an upgrade and downgrade function per version that changes the data structure.

Whenever you detect a new version with old version storage you apply all the `upgrade` functions for each proceeding version after the version stored consecutively:

Could look something like this:

```js
const migrations = [
    {
        version: 'x.x.x',
        upgrade: () => {
            // do stuff to upgrade
        },
        downgrade: () => {
            // do stuff to downgrade
        }
    },
    {
        version: 'x.x.x',
        upgrade: () => {
            // do stuff to upgrade
        },
        downgrade: () => {
            // do stuff to downgrade
        }
    },
    {
        version: 'x.x.x',
        upgrade: () => {
            // do stuff to upgrade
        },
        downgrade: () => {
            // do stuff to downgrade
        }
    },
    {
        version: 'x.x.x',
        upgrade: () => {
            // do stuff to upgrade
        },
        downgrade: () => {
            // do stuff to downgrade
        }
    },
    {
        version: 'x.x.x',
        upgrade: () => {
            // do stuff to upgrade
        },
        downgrade: () => {
            // do stuff to downgrade
        }
    }
]
```

**Comment by pascallapointe** [comment]
I actually need that feature to be able to push forward a new balance feature, so I will implement the migration system.

@sublayerio proposal fit the requirement, it's basically the same system i'm used to on php side.

Since extension storage isn't really fancy, that should be trivial to implement.
