### ISSUE TITLE
Fire Site Removal Event

### ISSUE THREAD

**Issue by cjkoepke** [Berry-Pool/nami-wallet#31]
Right now, if you connect the wallet, then the browser gets a response. However, if a user goes to Whitelisted Sites and removes a site, there is no callback that a website can use to perform an action (i.e. remove cached wallet data).

Suggestion: add an event for `onSiteRemoval` or something similar to allow browsers to react to this.

**Comment by alessandrokonrad** [comment]
Yep, this was already suggested: https://github.com/Berry-Pool/nami-wallet/issues/17
I follow mostly this CIP: https://github.com/cardano-foundation/CIPs/pull/88 right now.

**Comment by cjkoepke** [comment]
Awesome, I'll close and follow the other ticket. Thanks @alessandrokonrad
