### ISSUE TITLE
Improve Collateral Management

### ISSUE THREAD

**Issue by HeptaSean** [Berry-Pool/nami-wallet#312]
Currently, Nami does not even find collateral UTxOs created by itself on another device or before restoring a wallet.

This leads to prompts to create a new collateral UTxO, whenever a wallet is restored or another instance of Nami is spending the collateral, because *its* collateral UTxO is another one. This leads to transaction fees and fragmentation of the wallet.

Please implement a functionality like ccvault, where an existing UTxO in a sensible amount range can be taken as collateral.

**Comment by alessandrokonrad** [comment]
Hey, yes I added that in the most recent version 3.1.2. So if you haven't set collateral explicitely, it looks also for utxos now in the range of 5-50 ADA.

**Comment by HeptaSean** [comment]
That's good to know, but it still does not look for a fitting UTxO, when going to the “Collateral” menu item, but offers to create a new one.

I suppose, a lot of people will do that, which at least needlessly costs transaction fees.

It also means that this instance of Nami will probably take away the collateral UTxO of other instances of Nami (or other wallet apps) in “normal” transactions, which means that I can only use Nami for transactions that are *guaranteed* to require a collateral if I don't want that UTxO to be spent, so that I have to create yet another one.

It really should be possible to choose a specific UTxO in setting collateral in all wallet apps that are supposed to nicely cooperate.

**Comment by alessandrokonrad** [comment]
Yes there was a proposed CIP to do that, however after the next hard fork (Babbage), collateral utxos can also contain multi assets, which makes the coin selection much easier. This whole Collateral thing on the user side was only meant as a temporary solution in Nami and I will get rid of it very soon.

**Comment by HeptaSean** [comment]
Okay then. Closed for me.
