### ISSUE TITLE
Max limit of sub-accounts when restoring Nami wallet?

### ISSUE THREAD

**Issue by mwhang77** [Berry-Pool/nami-wallet#313]
I have a Nami wallet with roughly 25 sub-accounts that I recently restored but only 21 sub-accounts are displayed upon restore. Is there a limit to the number of sub-accounts that can be restored? If so, do I need to consolidate some accounts to get under the max number and then restore my wallet again?

**Comment by alessandrokonrad** [comment]
Hey there is no limit. When reimporting the wallet Nami tries to look for all your accounts. However when it finds a gap between your accounts, so basically an empty account with 0 tx history it assumes there are no more accounts and it will stop looking. You can simply recover these accounts by manually creating new accounts in Nami. They are all sequentially derived from the seed phrase, so you will always recover the same accounts in the same order when you create new accounts.

**Comment by mwhang77** [comment]
Thank you!
