### ISSUE TITLE
Doubt about assets

### ISSUE THREAD

**Issue by gerciljunio** [Berry-Pool/nami-wallet#319]
Hi, how should a coin be created so that it can appear in the Assets tab and not in the Collectibles tab in Nami Wallet?
For example, $PAVIA appears in assets while $cNETA appears in Collectibles and both are coins! Thanks!

One other little thing, your twitter github link is forwarding to "https://github.com/Berry-Pool/nam".

**Comment by alessandrokonrad** [comment]
People misuse metadata. They should use the 721 label only for NFTs and Collectibles, but they use it for other assets as well, which is wrong.

> One other little thing, your twitter github link is forwarding to "https://github.com/Berry-Pool/nam".

Thanks, I'll fix that.

**Comment by gerciljunio** [comment]
That's cool @alessandrokonrad , I didn't know that! I will research more about the correct way to create a currency. Thanks!
