### ISSUE TITLE
Add support for Token Native

### ISSUE THREAD

**Issue by BETOXL** [Berry-Pool/nami-wallet#32]
Congratulations on the wallet! I was looking at and it has no support for native tokens from the list https://nativetokens.da.iogservices.io/

**Comment by larryjcp** [comment]
+1 to this.
I got 1,000 "Alfonzo" tokens and 1,000 other native tokens in my Nami Wallet, and they are trapped, can't send it to other wallets! See attached screenshot, error "Asset quantity not set" could you please help?

![image](https://user-images.githubusercontent.com/8601954/135228178-bc84764e-2cbf-4c77-8285-c954267f4f0a.png)
