### ISSUE TITLE
I can't send the ada anywhere else.

### ISSUE THREAD

**Issue by chaehunyun** [Berry-Pool/nami-wallet#325]
I'm trying to send the ada I have, but I can't choose.If you select another coin, the send is displayed and you can send it, but only the ada is not selected.
Please let me know what the problem is.
"ada" doesn't show the send button.
Swap is normal with the ada you own, but if you select ada, the send button should appear below, but there is no response.Help me.

**Comment by uptick21** [comment]
Having the same issue - please help

**Comment by HeptaSean** [comment]
> If you select another coin, the send is displayed and you can send it, but only the ada is not selected. Please let me know what the problem is. "ada" doesn't show the send button.

Can you send ADA with the big yellow “Send” button next to “Receive” in the upper row?

In contrast to the other assets, it just does not seem to have a detail view (because it is just the main currency of the network?).
