### ISSUE TITLE
Missing accounts after Restoring seed phrase

### ISSUE THREAD

**Issue by Themcduckcryptoclub** [Berry-Pool/nami-wallet#338]
I had 5 accounts under one seed phrase. After restoring my seed phrase and downloading Nami on a new computer, I was only able to get access to 2 of the 5 accounts that I had created. I tried clicking on create new wallet in hopes that it would bring back the older ones, but it didn’t. Please help.

**Comment by Themcduckcryptoclub** [comment]
<img width="233" alt="97EECA66-115D-4EED-95C4-F89490038EBA" src="https://user-images.githubusercontent.com/93794277/151732795-d1216f34-acef-487b-a87a-58102f9180bd.png">

**Comment by Themcduckcryptoclub** [comment]
I tried to remove the Nami extension and put it back but I still have access to 2 out of the 5 total wallets…

**Comment by alessandrokonrad** [comment]
Check out this issue to find your answer #313

**Comment by Themcduckcryptoclub** [comment]
> Check out this issue to find your answer #313

Thank you, it worked!
