### ISSUE TITLE
Missing Sundae Tokens

### ISSUE THREAD

**Issue by Joec1981** [Berry-Pool/nami-wallet#340]
Last week I successfully completed a swap of ADA for Sundae.  The tokens were in my Nami wallet last week and not the asset Sundae does not show in my Nami Wallet. https://cardanoscan.io/transaction/63187c1ef9b626a75d5248092ad0d4d55fd78d2d99d61c70368649f7744fb30b

**Comment by edu-d-rai** [comment]
you sent them to another address here https://cardanoscan.io/transaction/1868ff501aae26bbdcb74ce21b903e802d4072e44a9d6fdbb90fd2061422b45b

**Comment by Joec1981** [comment]
it looks like I have 3 addresses attached to the account.  I have sent 319 Sundae to a liquidity pool so I should still have 245.84 left but it isnt showing in my Nami wallet https://cardanoscan.io/addresses?stakeKey=d65699f1ef4f36773de89d744d79621d5f3e0e41035d457e1c4b7673

**Comment by HeptaSean** [comment]
You have used the wallet with another wallet app than Nami. All other wallet apps use multiple addresses per wallet (a new unused change address for outgoing transactions, for example).

To make the contents reappear in Nami, just send everything to the first address (the one Nami shows as “Receive”) with that other wallet app.

If the other wallet app is ccvault, you can activate single address mode in the settings and it will cooperate more nicely with Nami.

If you also set a collateral for smart contracts, set it in Nami and then activate collateral in ccvault settings. It should pick up the collateral set aside by Nami and protect it from being spent in other transactions.
