### ISSUE TITLE
MELD sent from Daedalus to Nami was reduced 1,000,000x 

### ISSUE THREAD

**Issue by sdurig1** [Berry-Pool/nami-wallet#342]
According to Daedalus, I received 1,359,057,087 MELD tokens.  Since MELD doesn't pair with Daedalus, I had to send it to the NAMI wallet.  When I did, I noticed that the NAMI wallet counted it only as 1,359.057087.  In other words, it apparently reduced the amount of MELD I had sent by 1/1,000,000.  I'm trying to figure out if my Daedalus or my Nami is actually the correct amount.

**Comment by sigurdarson** [comment]
Nami shows the correct amount. In Daedelus you need to set the decimal amount to 6 as it's wrong by default.

**Comment by sdurig1** [comment]
> Nami shows the correct amount. In Daedelus you need to set the decimal amount to 6 as it's wrong by default.

I appreciate the help!
