### ISSUE TITLE
My wallet don't show the real ada

### ISSUE THREAD

**Issue by yass093** [Berry-Pool/nami-wallet#391]
Hello i have an issue i can't see my real ada in the wallet, i sent ada from binance i can't see it in nami but i see it in pool.pm or in cardanoscan
here two image of what i have in my wallet  
![image](https://user-images.githubusercontent.com/82773064/153761074-a7d7bd70-09f0-499b-9848-fd868b68d3eb.png)
![image](https://user-images.githubusercontent.com/82773064/153761084-2d826992-9c22-4571-8888-4b2e26d4783e.png)

can you help me to solve the problem !

**Comment by viavalbuena** [comment]
Hi i've had the same problem, did it show up? and how long did it take?
