### ISSUE TITLE
HOW TO DECODE USEDADDRESS FROM NAMIWALLET?

### ISSUE THREAD

**Issue by commedesvlados** [Berry-Pool/nami-wallet#40]
Can you tell me how to get this address from the wallet
![image](https://user-images.githubusercontent.com/68097698/129573657-2e3213f2-622d-42e2-a563-51851a91e97c.png)

I have this address:
![image](https://user-images.githubusercontent.com/68097698/129574225-e86e79c7-dc84-4345-acf5-aff93962c663.png)

When I connect the wallet to the site, I get this:
![image](https://user-images.githubusercontent.com/68097698/129574463-f0cf6f56-3015-4d7a-a820-b5a99b897709.png)

How do I decode a hex encoded bytes string? 
I will be very grateful!!!!!!!!!!!

**Comment by cjkoepke** [comment]
Are you trying to decode it in JS? There is a helpful library that serializes/deserializes strings from Emurgo: https://github.com/Emurgo/cardano-serialization-lib

**Comment by commedesvlados** [comment]
> Are you trying to decode it in JS? There is a helpful library that serializes/deserializes strings from Emurgo: https://github.com/Emurgo/cardano-serialization-lib

If you have already used this library, you could send a sample code to get the address please!

**Comment by commedesvlados** [comment]
I have this problem 
![image](https://user-images.githubusercontent.com/68097698/129710099-fac8d7ad-ed3d-4d03-9fb7-0985288f6d26.png)

**Comment by pixelheadsquad** [comment]
Hey @cjkoepke @commedesvlados, which API/functions from https://github.com/Emurgo/cardano-serialization-lib to use, to decode the Value is a hex encoded cbor string from `cardano.getBalance()` and the RewardAddress, a hex encoded bytes string?

**Comment by jinglescode** [comment]
Hey @cjkoepke @commedesvlados, which API/functions from https://github.com/Emurgo/cardano-serialization-lib to use, to decode the Value is a hex encoded cbor string from `cardano.getBalance()` and the RewardAddress, a hex encoded bytes string?
