### ISSUE TITLE
Can't withdraw rewards

### ISSUE THREAD

**Issue by QCPOLstakepool** [Berry-Pool/nami-wallet#44]
I have ~360 Ada in rewards and Nami says I can't withdraw:

![image](https://user-images.githubusercontent.com/77652463/131251684-95165062-4d27-4ad5-b560-0275675e43e5.png)

**Comment by alessandrokonrad** [comment]
This is an issue with version 1.1.3. Version 1.1.4 should be out soon that fixes this again

**Comment by alessandrokonrad** [comment]
1.1.4 is out now. Let me know if it works now and then we can close the issue.

**Comment by QCPOLstakepool** [comment]
I will test again next epoch as I withdrew rewards with Daedalus.

**Comment by QCPOLstakepool** [comment]
Can confirm that it works now. Thanks!
