### ISSUE TITLE
Missing key hashes from tx.body().collateral()

### ISSUE THREAD

**Issue by kk-kien** [Berry-Pool/nami-wallet#464]
## Summary

When Nami is requested to sign, it will check if the signature is necessary. If not needed, it will show an error "Signature not possible".

The problem is that Nami only checks the key hashes from:
- `tx.body().inputs()`
- `tx.body().certs()`
- `tx.body().required_signers()`

It does not check `tx.body().collateral()`.

## Example

Consider this transaction:

```
84a600818258201dc5099c5ace3d654839eb261dd61248a0b21d831e58372805f60b1e41bb808b01018182583900d25e503b20ea4d2041f438f7d5d330237bf1158d46bb72af8927319b9ecddc250241cfce5a34c6601ee0b3e5ef71542561443c1a07dc69911a055ab19e021a000298e20b5820b855f37df89c8d84e42d970f00455c7b001b50c2211dc6f5f8e432c39dc9efbc0d818258200c153f47be46b76d1df3b46c9d2532c3b0adb8817a06978d10d7089edf413f17000e80a303814e4d010000332222200512001200110481191a0a05818400001a6b69656e821906a41a00074534f5f6
```

When requested to sign, Nami rejects and shows

```
Signature not possible
```

Without signing, this tx will fail at submission:

```
{"code":2,"info":"Wallet could not send the tx.","message":"\"transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (MissingVKeyWitnessesUTXOW (WitHashes (fromList [KeyHash \\\"d25e503b20ea4d2041f438f7d5d330237bf1158d46bb72af8927319b\\\"]))))])\""}
```

As a consequence, the tx cannot be submitted.

## Suggested fix

In `src/ui/app/pages/signTx.jsx`,

```
const getKeyHashes = (tx, utxos, account) => {
  let requiredKeyHashes = [];
  ...
  // check tx.body().collateral() as well
  ...
}
```

**Comment by kk-kien** [comment]
@alessandrokonrad

**Comment by kk-kien** [comment]
Let me explain the transaction above.

```
84a600818258201dc5099c5ace3d654839eb261dd61248a0b21d831e58372805f60b1e41bb808b01018182583900d25e503b20ea4d2041f438f7d5d330237bf1158d46bb72af8927319b9ecddc250241cfce5a34c6601ee0b3e5ef71542561443c1a07dc69911a055ab19e021a000298e20b5820b855f37df89c8d84e42d970f00455c7b001b50c2211dc6f5f8e432c39dc9efbc0d818258200c153f47be46b76d1df3b46c9d2532c3b0adb8817a06978d10d7089edf413f17000e80a303814e4d010000332222200512001200110481191a0a05818400001a6b69656e821906a41a00074534f5f6
```

This transaction has:
- 1 input: `{ "txId": "1DC5099C5ACE3D654839EB261DD61248A0B21D831E58372805F60B1E41BB808B", "txIdx": 1 }`
- 1 output: `{ "address": "00D25E503B20EA4D2041F438F7D5D330237BF1158D46BB72AF8927319B9ECDDC250241CFCE5A34C6601EE0B3E5EF71542561443C1A07DC6991", "quantity": 89829790 }`

**Comment by kk-kien** [comment]
From Alonzo era, the signature from collateral owner is required:

```
eras/alonzo/impl/src/Cardano/Ledger/Alonzo/Rules/Utxow.hs:
  377      txbody = getField @"body" tx
  378:     inputAuthors :: Set (KeyHash 'Witness (Crypto era))
  379:     inputAuthors =
  380:       foldr
  381:         accum
  382:         Set.empty
  383:         ( getField @"inputs" txbody
  384:             `Set.union` getField @"collateral" txbody
  385:         )
  386        where
```

**Comment by alessandrokonrad** [comment]
https://github.com/Berry-Pool/nami-wallet/commit/5647bead6467a2f790dce2cdba1a949d931aee38
Just made the changes in this last commit. Are you able to test it yourself with a local version of Nami?

**Comment by kk-kien** [comment]
> [5647bea](https://github.com/Berry-Pool/nami-wallet/commit/5647bead6467a2f790dce2cdba1a949d931aee38)
> Just made the changes in this last commit. Are you able to test it yourself with a local version of Nami?

Thanks for the prompt response. I have never tried to build nami-wallet by myself. Let me read the commit.

**Comment by kk-kien** [comment]
The code change is not trivial. I guess I have to build locally and test it.

**Comment by kk-kien** [comment]
I will do it tomorrow because I have a demo tonight. If you are confident, please proceed to release the new version.

**Comment by kk-kien** [comment]
Unable to reproduce the issue now. Closing.
