### ISSUE TITLE
Nami Wallet missing funds

### ISSUE THREAD

**Issue by Tim68-stef** [Berry-Pool/nami-wallet#505]
I sent 3 transactions from Metamask to Nami quick succession. The first 2 tx went through fine.
The 3rd transaction from Metamask was confirmed 4 hours ago to Nami but the funds haven't shown up. 
Its a large sum of money. Please help recover the funds.
public address sent to: 0x98981F053dc441b919a5f213A3F96c37cd620889
network: milkomeda cardano c1
transaction id: 0xcaff43fdd14dbf9c3e21f395bc17d8ea262219717f0f2c64c6607ae7a1712e74

**Comment by alessandrokonrad** [comment]
If you can see the transaction in a cardano explorer like cardanoscan.io , everything is fine. If not it seems like they are stuck in the bridge of Milkomeda. Could you let me know your Cardano address?

**Comment by Tim68-stef** [comment]
Thank you for responding. I was really worried last night as it was over 10 hours of waiting. When I woke up this morning the funds were there. I really appreciate your help.
