### ISSUE TITLE
Image URLs that are split into arrays in metadata do not render in Nami wallet

### ISSUE THREAD

**Issue by DanTup** [Berry-Pool/nami-wallet#52]
I'm having issues with assets not rendering their images correctly which I believe is related to them being an array. The CIP for 721 metadata, it says image can be a URI or an array:

https://github.com/cardano-foundation/CIPs/blob/8b1f2f0900d81d6233e9805442c2b42aa1779d2d/CIP-NFTMetadataStandard.md

```
"image": <uri | array>,
```

My IPFS URLs are > 64 chars, so I split them into an array like this:

```
         image: [
            "ipfs://bafkreighf2nnlrg25yyf7u47gfgexj5jywzuyj6wlvp7uh2ofz2c2jqi",
            "g4"
         ],
```

However, they fail to render in nami wallet. If I inspect the page, I see that the URL being requested is like:

```
https://ipfs.blockfrost.dev/ipfs/bafkreighf2nnlrg25yyf7u47gfgexj5jywzuyj6wlvp7uh2ofz2c2jqi,g4
```

The comma near the end looks suspicious. It looks like this might have been fixed by b19439815d217247a001bb17884bfe0a90ade288 but that shipped in 1.1.3 and I'm using 1.1.5. I wonder if perhaps there's another place that needs this - perhaps line 47 here? (I'm not sure of the difference between `result.metadata and result.on_chain_metadata):

https://github.com/Berry-Pool/nami-wallet/blob/b19439815d217247a001bb17884bfe0a90ade288/src/ui/app/components/asset.jsx#L41-L48

**Comment by DanTup** [comment]
Actually, I think this might be a Blockfrost issue:

```
{
	"asset": "b293e143989c49f1b15b5584e03bc12b26dcd2e693e615d638f052344f76616c506572736f6e343038",
	"policy_id": "b293e143989c49f1b15b5584e03bc12b26dcd2e693e615d638f05234",
	"asset_name": "4f76616c506572736f6e343038",
	"fingerprint": "asset1fjuxqmcqjdthw8uahjyjx2twm9wpn3h9nw6ycg",
	"quantity": "1",
	"initial_mint_tx_hash": "1c283c1327143d3cccf47d24cf2d7db44734b7389e99e578f06a602d1e210881",
	"mint_or_burn_count": 1,
	"onchain_metadata": {
		"image": "ipfs://bafkreiawd5zzckftdxoalvuqnzolc3cws7b2vn35iotw5bsbc7ffsfyy,cq",
	},
	"metadata": null
}
```

**Comment by 1000101** [comment]
> I've sent Blockfrost an email to see if they agree and may fix this.

Thanks a lot, fix is already in place along with Alonzo hard-fork ;).

**Comment by DanTup** [comment]
Is there something I need to do to clear cached data in Nami? I'm still seeing currently requests for the bad URLs (though I'm not certain if it's cached data or blockfrost still returning the bad URLs).

**Comment by DanTup** [comment]
@1000101 I'm still seeing the same issue calling the API today:

<img width="831" alt="Screenshot 2021-09-13 at 07 32 09" src="https://user-images.githubusercontent.com/1078012/133034836-f00b062a-fd82-4be3-8a05-869e41b2c540.png">

Asset is: https://cardano-testnet.blockfrost.io/api/v0/assets/b293e143989c49f1b15b5584e03bc12b26dcd2e693e615d638f052344f76616c506572736f6e343038

This is a newly-minted one so caching shouldn't be a factor. Any ideas?

**Comment by 1000101** [comment]
> @1000101 I'm still seeing the same issue calling the API today:
> 
> <img alt="Screenshot 2021-09-13 at 07 32 09" width="831" src="https://user-images.githubusercontent.com/1078012/133034836-f00b062a-fd82-4be3-8a05-869e41b2c540.png">
> 
> Asset is: https://cardano-testnet.blockfrost.io/api/v0/assets/b293e143989c49f1b15b5584e03bc12b26dcd2e693e615d638f052344f76616c506572736f6e343038
> 
> This is a newly-minted one so caching shouldn't be a factor. Any ideas?

Could you please try it now? It should be completely rolled out on testnet.

**Comment by DanTup** [comment]
@1000101 it works - thank you! :-)

**Comment by DanTup** [comment]
@1000101 do you know if the fix ever made the mainnet API? I'm seeing broken images on cnft.io that seem to be because the last few characters of the URL is missing (the ones that would be in the second part of the string) but I'm not sure if it's the same API bug, or if cnft.io are interpreting the raw data and incorrectly building the URL.

**Comment by 1000101** [comment]
> @1000101 do you know if the fix ever made the mainnet API? I'm seeing broken images on cnft.io that seem to be because the last few characters of the URL is missing (the ones that would be in the second part of the string) but I'm not sure if it's the same API bug, or if cnft.io are interpreting the raw data and incorrectly building the URL.

Yes it did, 18 days ago. Can you provide a sample please?

**Comment by DanTup** [comment]
@1000101 unfortunately there isn't a way I can link to it - or see the API calls. They're fetching the data server-side and what's coming back to the client is just missing the last few characters.

If you've deployed your fix, then I wonder if they're constructing the URL themselves and only taking the first item of the array. I've sent a ticket through their site to see what they say anyway. The asset in question is https://cardanoscan.io/token/807fc28247e6837792ed8b9cee0183c962527d3965cb80a682bb4f8054686543617264616e6f436c6f776e3938.

It renders fine on pool.pm. I can't easily test with Nami as it's on a hardware wallet. If you know of any sites using Blockfrost API/IPFS Gateway that let me browse arbitrary assets, perhaps that would confirm it's not Blockfrost and just cnft.io.

**Comment by 1000101** [comment]
> @1000101 unfortunately there isn't a way I can link to it - or see the API calls. They're fetching the data server-side and what's coming back to the client is just missing the last few characters.
> 
> If you've deployed your fix, then I wonder if they're constructing the URL themselves and only taking the first item of the array. I've sent a ticket through their site to see what they say anyway. The asset in question is https://cardanoscan.io/token/807fc28247e6837792ed8b9cee0183c962527d3965cb80a682bb4f8054686543617264616e6f436c6f776e3938.
> 
> It renders fine on pool.pm. I can't easily test with Nami as it's on a hardware wallet. If you know of any sites using Blockfrost API/IPFS Gateway that let me browse arbitrary assets, perhaps that would confirm it's not Blockfrost and just cnft.io.

From what I can tell the asset is returned correctly:

```
{
  "asset": "807fc28247e6837792ed8b9cee0183c962527d3965cb80a682bb4f8054686543617264616e6f436c6f776e3938",
  "policy_id": "807fc28247e6837792ed8b9cee0183c962527d3965cb80a682bb4f80",
  "asset_name": "54686543617264616e6f436c6f776e3938",
  "fingerprint": "asset16zmuqq6l2hh69z73l89ywxpuxnhzyg6qs96pgx",
  "quantity": "1",
  "initial_mint_tx_hash": "da0f54be03b4224fbc50b7a4dad5bdfee18b972be6b7798043218cd521db01d9",
  "mint_or_burn_count": 1,
  "onchain_metadata": {
    "name": "The Cardano Clown #98",
    "image": [
      "ipfs://bafybeidmtptmze3d6ow6s3k5nbmujiebsbng5yo2qk2e55vzavvizuqy",
      "b4"
    ],
    "traits": [
      "Orange and Green Outfit",
      "Red Hair",
      "Yellow Balloon",
      "Mobile Phone"
    ],
    "website": "https://thecardanoclowns.com/"
  },
  "metadata": null
}

```

IPFS is rendering OK as well:
https://ipfs.blockfrost.dev/ipfs/bafybeidmtptmze3d6ow6s3k5nbmujiebsbng5yo2qk2e55vzavvizuqyb4

So I guess it could be URL parsing / constructing issue.

**Comment by DanTup** [comment]
@1000101 yep, that looks correct to me too. My guess is CNFT isn't handling images that are arrays of strings correctly then (and are just taking the first element).

I'll follow up with them on their ticket. Thanks for your help!

**Comment by 1000101** [comment]
> @1000101 yep, that looks correct to me too. My guess is CNFT.io isn't handling images that are arrays of strings correctly then (and are just taking the first element).
> 
> I'll follow up with them on their ticket. Thanks for your help!

Thanks, let me know how it goes!
