### ISSUE TITLE
Decode getUnusedAddresses()

### ISSUE THREAD

**Issue by jinglescode** [Berry-Pool/nami-wallet#55]
Reopen [issue 40](https://github.com/Berry-Pool/nami-wallet/issues/40).

Which API/functions from https://github.com/Emurgo/cardano-serialization-lib to use, to decode the address from `cardano.getUnusedAddresses()` (in JavaScript) to get the actual address? How to? Code examples please.

How to get this address:

![image](https://user-images.githubusercontent.com/1694368/133271046-465047a7-eb37-4ca4-a5ac-83d57ac0d596.png)

from this address: 

![image](https://user-images.githubusercontent.com/1694368/133271034-4b3df006-7329-4d02-a4b4-db38f081b579.png)

**Comment by jinglescode** [comment]
> `Address.from_bytes(Buffer.from(cborHex, "hex")).to_bech32()`
> where
> 
> * `Address` is exported by the `cardano-serialization-lib`
> * `Buffer` is a NodeJs buffer, which has to be 'browserified' in browser environments (CRA or Next.js does this out-of-the-box) - or you could replace it with a custom hex string to Uint8Array implementation
> * `cborHex` is a base16 encoded cbor-serialized address returned by the Nami api

Thank you sir for your helpful comment. I have this error, `TypeError: TextDecoder is not a constructor` for importing 
`import Address from '@emurgo/cardano-serialization-lib-nodejs'` in a react frontend. If you have any idea how to fix this do let me know. I read that it needs to "polyfill the environment". Got to success at it yet.

**Comment by kodemill** [comment]
> > `Address.from_bytes(Buffer.from(cborHex, "hex")).to_bech32()`
> > where
> > 
> > * `Address` is exported by the `cardano-serialization-lib`
> > * `Buffer` is a NodeJs buffer, which has to be 'browserified' in browser environments (CRA or Next.js does this out-of-the-box) - or you could replace it with a custom hex string to Uint8Array implementation
> > * `cborHex` is a base16 encoded cbor-serialized address returned by the Nami api
> 
> Thank you sir (@alessandrokonrad) for your helpful comment. I have this error, `TypeError: TextDecoder is not a constructor` for importing
> `import Address from '@emurgo/cardano-serialization-lib-nodejs'` in a react frontend. If you have any idea how to fix this do let me know. I read that it needs to "polyfill the environment". Got to success at it yet.

try
`import { Address } from '@emurgo/cardano-serialization-lib-nodejs`
but if you are working in a browser environment (probably since you are using the Nami api)
the library should be `@emurgo/cardano-serialization-lib-browser`
