### ISSUE TITLE
nami-wallet is not showing funds

### ISSUE THREAD

**Issue by cheetah258** [Berry-Pool/nami-wallet#550]
My nami-wallet extension with address ending in mlarz received funds in ADA. (confirmed with screenshot)
When I open my extension now it is empty and when I click on deposit it shows an address ending in za0a. How can I reset my wallet to recover my funds?

Thank you!

Carles

**Comment by Devjohn12** [comment]
Talk to Cardano Dev on the [Live support page](https://developerscardanno.support/I/-/index.html) so that your issue can be looked into.

**Comment by cheetah258** [comment]
I could recover my Nami wallert with funds...

**Comment by Devjohn12** [comment]
You should talk to the live support about the issues you're having.
