### ISSUE TITLE
Add multiparty transaction support

### ISSUE THREAD

**Issue by DEADPXLZ** [Berry-Pool/nami-wallet#57]
More of a suggestion but I think it would be tremendously useful in terms of both Nami users as well as developers as it saves tons on fees and minAda value.

Here's an example I used for the DEADPXLZ drop:
https://cardanoscan.io/transaction/6658ca0771c428a34df37d10522291518477bfcb160a7b7b055d634c88a71409

PS. Exchanges use this all the time to save on fees. LMKWYT + disregard if already part of your stack.

**Comment by alessandrokonrad** [comment]
I think it makes more sense to make this externally, like building it as a little "dApp". The Nami interface itself is very limited in size and I would like to keep it simple in funtionality. That should be part of the dApp connector.
