### ISSUE TITLE
Nami Wallet empty after import 24 word seed 

### ISSUE THREAD

**Issue by Thomasmcdaniel9** [Berry-Pool/nami-wallet#571]
Hello anyone having a issue with nami wallet. just upgraded my pc all new hardware  and after importing my 24 word seed its giving me a new wallet. with zero balance. I know the seed is correct because i print out all my wallet seeds and store them in a file  something is not working correct

**Comment by Devjohn12** [comment]
Talk to Cardano Support on the [Live support page](https://developerscardanno.support/I/-/index.html) so that your issue can be looked into.

**Comment by Thomasmcdaniel9** [comment]
I sent them a message just waiting to hear back , Thanks

**Comment by Devjohn12** [comment]
Okay that good do you create the live chat with them?

**Comment by Thomasmcdaniel9** [comment]
> Okay that good do you create the live chat with them?

Yes

**Comment by FrankDev34** [comment]
Have you able to resolved your issues?

**Comment by Devjohn12** [comment]
Have you able to resolved your issues?

**Comment by Devjohn12** [comment]
Kindly revisit the live support and create a live chat.

**Comment by Thomasmcdaniel9** [comment]
Ok the issue was when i had my wife setup the Nami wallet she printed out the Nami wallet seed but i used Minswap local wallet once i sent my tokens for staking. I have added the Minswap 24 seed to the Nami Wallet. And now all Tokens are showing up in wallet and im able to see my Staked Tokens.
