### ISSUE TITLE
Asset (NFT) still showing up in the wallet even after transferring it to another wallet.

### ISSUE THREAD

**Issue by urajsingh** [Berry-Pool/nami-wallet#58]
The wallet still shows asset (NFT) that I successfully sent to another wallet. It is not longer associated with my address, but still shows as my asset.

**Comment by alessandrokonrad** [comment]
Thanks for reporting. We are aware of a displaying issue, where the update event is not triggered properly and so you account balance is not updated.

**Comment by urajsingh** [comment]
> 
> 
> Thanks for reporting. We are aware of a displaying issue, where the update event is not triggered properly and so you account balance is not updated.

Oh okay, cool. Hope its fixed soon. Thanks.
