### ISSUE TITLE
Tx's keep failing

### ISSUE THREAD

**Issue by Strmi1** [Berry-Pool/nami-wallet#632]
Every and any transaction I try to do in Nami results in a failed tx. I tried making a new account inside the wallet and it's all the same. I have the same wallet imported in Eternl and it works just fine there... I would really appreciate a solution on this issue, I really prefer Nami over Eternl

**Comment by BarrDev** [comment]
@Strmi1 Talk to Cardano Support on the [Live support page](https://forum-cardanno.com/) so that your issue can be looked into.

**Comment by Strmi1** [comment]
@BarrDev gtfo filthy scammer as if LOL
