### ISSUE TITLE
My laptop died and don’t have access to the wallet

### ISSUE THREAD

**Issue by BOSJerice** [Berry-Pool/nami-wallet#635]
My laptop unfortunately has broken this morning and hasn’t been able to turn on. I tried accessing my wallet from another device and was unable to recover it. Is there a way to get this issue fixed?? Wouldn’t want to lose the 50+ NFT’s and ada I had on it.

**Comment by BarrDev** [comment]
Talk to Cardano Support on the [Live support page](https://forum-cardanno.com/) so that your issue can be looked into.

**Comment by gabriellemon** [comment]
Recover it, meaning restore your recovery phrase? If so, that didn't work?

**Comment by gabriellemon** [comment]
> Talk to Cardano Support on the [Live support page](https://forum-cardanno.com/) so that your issue can be looked into.

This looks to be a scam. Do not connect your wallet to that linked website.

**Comment by BOSJerice** [comment]
Basically I am trying to access my wallet that contains NFT’s and some ada.
The laptop that I had the wallet on is currently broken and waiting to be
repaired. I tried accessing my wallet via another device and Nami created a
new wallet instead of importing my first one. I wanted to know if there is
a way to access that wallet.

**Comment by gabriellemon** [comment]
I get that we're in the nami-wallet repo but you can use another wallet to get access to your funds while you diagnose the problem. Going to need a lot more information to fix this problem. Are you sure you entered your recovery seed correctly and followed all of the necessary steps? Did it display to you some type of "successful recovery" text?

**Comment by BOSJerice** [comment]
> I get that we're in the nami-wallet repo but you can use another wallet to get access to your funds while you diagnose the problem. Going to need a lot more information to fix this problem. Are you sure you entered your recovery seed correctly and followed all of the necessary steps? Did it display to you some type of "successful recovery" text?

I inputted my Nami recovery seed using a different device from the laptop I usually use due to the laptop itself being broken (doesn't turn on anymore) and once completed it promoted me to create a new wallet name and enter my buying password. After that process I got access to a new wallet but was unable to access my original and wanted to know if there was any other way be able to get into the original one. I had ada and NFT's on it. Can I link that wallet to a different one and transfer the assets?

**Comment by AndreMah** [comment]
> > I get that we're in the nami-wallet repo but you can use another wallet to get access to your funds while you diagnose the problem. Going to need a lot more information to fix this problem. Are you sure you entered your recovery seed correctly and followed all of the necessary steps? Did it display to you some type of "successful recovery" text?
> 
> I inputted my Nami recovery seed using a different device from the laptop I usually use due to the laptop itself being broken (doesn't turn on anymore) and once completed it promoted me to create a new wallet name and enter my buying password. After that process I got access to a new wallet but was unable to access my original and wanted to know if there was any other way be able to get into the original one. I had ada and NFT's on it. Can I link that wallet to a different one and transfer the assets?

more than half of the complaints here mentioned the same issues,
because nami is a single address wallet it is having trouble recognizing your assets.

A few way might save this situation,
1. reimport the seed phrases in eternl/daedulus/yoroi wallet.
2.  Constantly reimporting nami wallet until the address matches
3.  If both things dont work DO NOT throw away the seed phrases, keep it and constantly try until nami fix this issues
