### ISSUE TITLE
NFTs no longer showing under collectibles.

### ISSUE THREAD

**Issue by DogPro88** [Berry-Pool/nami-wallet#640]
As of yesterday my NFTs are no longer showing up in my NAMI wallet. I'm using a hardware wallet with this NAMI account. When I look on pool.pm the NFTs still show up. i deleted the wallet and restored but the issue was not resolved. I also transferred another NFT from secondary NAMI wallet as a test and that NFT did show under my NAMI hardware wallet account. How do I resolve this issue to gain access to my NFTs? Thanks!

**Comment by DogPro88** [comment]
Wow great support

**Comment by BarrDev** [comment]
Have you able to resolved your issues? @DogPro88
