### ISSUE TITLE
Restore Wallet

### ISSUE THREAD

**Issue by RoyandGloria** [Berry-Pool/nami-wallet#69]
Can I restore my wallet after resetting it？

**Comment by alessandrokonrad** [comment]
Yes, but always better to double check that you have written down the seed phrase correctly. Import the seed phrase in another wallet or in another Nami Wallet and check if get the right wallet.

**Comment by RoyandGloria** [comment]
The wallet I just reset has dollars. Even if I import the seed phrase correctly now, I can only create a new account. It seems that I can't find the wallet with dollars. Please help me，thank you.

**Comment by alessandrokonrad** [comment]
The sub accounts you create are the same ones you had before. They are indexed. First account is 0, next account is 1 and so on. You will always derive the same sub accounts again.

**Comment by rbellamy** [comment]
@alessandrokonrad sorry for necro-bumping a thread - but this is very interesting to me. Could you unpack the sentence "You will always derive the same sub accounts again?"

Is it that you will always derive the same sub accounts using the seed phrase (which is used to reconstruct the original Nami wallet)? Or are you saying something else?

**Comment by alessandrokonrad** [comment]
Yes that's exactly the case. The wallet recovery and sub account derivation is deterministic. Same seed phrase as input and you will always get the same accounts and the same order.
