### ISSUE TITLE
Unable to reset my wallet

### ISSUE THREAD

**Issue by renaldamaria** [Berry-Pool/nami-wallet#88]
I am unable to reset my wallet.
When I select the reset option, nothing happens.

**Comment by alessandrokonrad** [comment]
Thanks for letting me know. Should be resolved now in the latest version 2.2.2

**Comment by renaldamaria** [comment]
I'm trying to reset my password using my seed phrase.
I clicked the reset button, the page blinked, but nothing else.
Is there something else I need to do?
I'm using the Chrome extension.

**Comment by alessandrokonrad** [comment]
That's it. You have reset the wallet and can reimport it now
