### ISSUE TITLE
Where is my ADA?

### ISSUE THREAD

**Issue by keishyo** [Berry-Pool/nami-wallet#89]
I make 2 transactions 5ADA for each. But Nami wallet doesn't show up real 10ADA. Where is my remaining ADA?
1st transaction:
[https://explorer.cardano.org/en/transaction?id=155624e81b1afd6c6e54dd1ce6f285b048e3b3471e3bbfa682a4e7312a96ac53](url)
2nd transaction:
[https://explorer.cardano.org/en/transaction?id=6fb987b0ac98b588d5667dacbd427ce8c127da8a1e4bee23a42bd6132eec5c7d](url)
Pics:
![image](https://user-images.githubusercontent.com/93994235/140943081-377cd729-9587-4fd8-a09e-96a31f7c384a.png)
![image](https://user-images.githubusercontent.com/93994235/140943131-61e1618b-6191-4917-8db5-a84ce7419ae7.png)

**Comment by pascallapointe** [comment]
Nami wallet doesn't support multi-addresses, this is a design decision to keep the wallet fast & light.

If you used addresses displayed in another wallet than Nami, the ADA have been sent under another address of the same wallet, but Nami won't be able to use it, thus the warning message you are experiencing.

Nami only use the address index 0, it is always the same address. Looking at the transaction you made, ADA have been sent to 2 different addresses:

- addr1qy6f5rq2th2qpkqe96am444sjejhdh99lnkcdtcnm3vznt38rdg2sjnmvlyk92fqav0fhh2nvy6j0jjktyd757xl64dq5h88yg
- addr1qxrwkg3htk6wrmph38nj4dlu07ptal40vcutu4fah5lk7np8rdg2sjnmvlyk92fqav0fhh2nvy6j0jjktyd757xl64dq2n3jne

Both addresses hold 5ADA, but Nami will only show you the balance of the 1rst one. You will have to use another wallet to use full balance.

An option would be to use Yoroi and make a transaction to yourself. Sending all your assets to the address displayed in Nami will consolidate all your funds under the address supported by Nami.

Know that using again the same wallet seed under another vendor (Yoroi, Daedalus, etc.) will break again Nami by splitting your funds on multiples addresses.

**Comment by keishyo** [comment]
> Nami wallet doesn't support multi-addresses, this is a design decision to keep the wallet fast & light.
> 
> If you used addresses displayed in another wallet than Nami, the ADA have been sent under another address of the same wallet, but Nami won't be able to use it, thus the warning message you are experiencing.
> 
> Nami only use the address index 0, it is always the same address. Looking at the transaction you made, ADA have been sent to 2 different addresses:
> 
> * addr1qy6f5rq2th2qpkqe96am444sjejhdh99lnkcdtcnm3vznt38rdg2sjnmvlyk92fqav0fhh2nvy6j0jjktyd757xl64dq5h88yg
> * addr1qxrwkg3htk6wrmph38nj4dlu07ptal40vcutu4fah5lk7np8rdg2sjnmvlyk92fqav0fhh2nvy6j0jjktyd757xl64dq2n3jne
> 
> Both addresses hold 5ADA, but Nami will only show you the balance of the 1rst one. You will have to use another wallet to use full balance.
> 
> An option would be to use Yoroi and make a transaction to yourself. Sending all your assets to the address displayed in Nami will consolidate all your funds under the address supported by Nami.
> 
> Know that using again the same wallet seed under another vendor (Yoroi, Daedalus, etc.) will break again Nami by splitting your funds on multiples addresses.

Thank you so much.
