### ISSUE TITLE
Bug where collateral is used up while interacting with smart contracts

### ISSUE THREAD

**Issue by BlakeBrown** [Berry-Pool/nami-wallet#92]
Hi @alessandrokonrad! Thanks for making such a killer wallet 😄 

I'm the developer of [jpg.store](https://www.jpg.store/) and we've had two users run into issues with collateral.

Case 1: A user set collateral, and without removing it the UTXO somehow disappeared from their wallet.

<img width="1704" alt="Screen Shot 2021-11-11 at 6 28 00 PM" src="https://user-images.githubusercontent.com/6283620/141536578-c4111bee-d56d-4cc3-97fd-0a4b2a972525.png">

Case 2: I've also seen in some instances a user will have collateral UTXO in their wallet, but Nami doesn't seem to recognize it and requires them to reset it.

Any idea of why this might be happening? Could `cardano.getUtxos()` be including the collateral UTXO?

**Comment by alessandrokonrad** [comment]
Hey, I'll look into this. Maybe I forgot something, since I simply seperate the collateral UTxO from the other UTxO, but maybe there is something going wrong and so the collateral is consumed as normal UTxO.
Could you let me know which Nami version the users are on. I had a bug a few week ago, which I already fixed.

**Comment by BlakeBrown** [comment]
Thanks for checking! Will let you know the version the next time someone runs into this issue

**Comment by BlakeBrown** [comment]
Okay got it! Here's some more debugging info if it helps:

Nami version: `2.2.2`
Error: 
```"transaction submit error ShelleyTxValidationError ShelleyBasedEraAlonzo (ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (BadInputsUTxO (fromList [TxInCompact (TxId {_unTxId = SafeHash \"ecb8427cacfd1bdb8a5585b14418fc9c968fe727fa0afb1b5de8c5a20427e35f\"}) 0])))),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure NoCollateralInputs)),UtxowFailure (WrappedShelleyEraFailure (UtxoFailure (InsufficientCollateral (Coin 0) (Coin 1233572))))])"```
CBOR: https://gist.github.com/BlakeBrown/d83d010e53bc7f43b6e42ba998c405fe

User's wallet: 
![image](https://user-images.githubusercontent.com/6283620/141698332-63b9c5b8-f174-4812-84d6-89b61fefc239.png)

User's collateral UI:
![image](https://user-images.githubusercontent.com/6283620/141698338-d68485af-5545-48b1-a1e4-d1678331a855.png)

**Comment by alessandrokonrad** [comment]
Okay since the bug was in previous version he may have spent the collateral utxo normally already. That's why it's still wrong in the new version. Simply removing and readding should fix it. Then this behaviour should not happen again (hopefully).

**Comment by BlakeBrown** [comment]
Tentatively closing.
