### ISSUE TITLE
Question - signTx() documentation

### ISSUE THREAD

**Issue by edge2ipi** [Berry-Pool/nami-wallet#95]
Hi, thanks for the wallet!

Can you review the doco under **cardano.signTx(tx, partialSign)**, it has "_Transaction is a hex encoded cbor string._" however under the hood it requires Hex bytes [i.e. at api/extension/index.js:745 => _rawTx=Loader.Cardano.Transaction.from_bytes(Buffer.from(tx,'hex'));_. 

Indeed I needed to provide the latter for it to work. This is the error when providing cbor hex:
"_code: -1
info: "Inputs do not conform to this spec or are otherwise invalid."_"

Thanks

**Comment by alessandrokonrad** [comment]
Hey!
I'm not sure what you mean exactly? The function takes a hex string, not an array of bytes.

**Comment by timmyedge** [comment]
Hi, just that it isn’t cbor encoded?

**Comment by rooooooooob** [comment]
@edgeeipi yes it's hex-encoded CBOR bytes. plese refer to the [CIP-0030](https://github.com/cardano-foundation/CIPs/pull/88) standard.
