### ISSUE TITLE
Cannot add collateral with Ledger X

### ISSUE THREAD

**Issue by tdiesler** [Berry-Pool/nami-wallet#96]
Although Ledger works for send/withdraw, I cannot add collateral. The "Confirm" button is greyed out and the "Connect Ledger" button is disabled.

I would expect the "Connect Ledger" to be greyed or not visible (because I am connected) and the "Confirm" button to be active.

Version: 2.2.2

**Comment by alessandrokonrad** [comment]
Yeah it's disabled because HW can't interact with plutus. So adding collateral at this point would be unnecessary, that's why I disabled it for now.

**Comment by tdiesler** [comment]
Ok, thanks

**Comment by Simonlam999** [comment]
Hi. I am facing the same issue. Can i check if it will be switched on eventually? i will need it to utilise Sundaeswap. Otherwise, i would have to leave nami unfortunately. =(

**Comment by pascallapointe** [comment]
Ledger & Trezor need to update their firmware to support Cardano smart contract.
The feature will be added once supported by hardware wallet.

**Comment by grosu** [comment]
Any news on when Ledger will update their firmware to support Cardano smart contracts?  And once that happens, how long it will take until Nami supports them, too?  Without this feature, many users will not be able to use Nami with Sundaeswap, especially larger liquidity providers who only operate using HW wallets.  @Simonlam999 is there any other option than Nami to use a HW wallet with Sandaeswap?

**Comment by Simonlam999** [comment]
@grosu No other option if firmware doesn't support cardano smart contract. our only hope lies in Ledger, who appears to be in no hurry. I guess we got to go without ledger support. Scary!

**Comment by alessandrokonrad** [comment]
> how long it will take until Nami supports them, too?

We could provide support instantly, it's really just a thing on the ledger/trezor software side, where we have no influence on.

**Comment by fungilation** [comment]
So after Ledger eventually add plutus support. Nami wallet setup can also then add import from connected Ledger HW?

I'm coming from staking my ADA from my ledger wallet for the Meld ISPO, and Meld currently only support Nami for interacting/staking Meld.
