### ISSUE TITLE
getUtxos returns only 8 items

### ISSUE THREAD

**Issue by rosieks** [Berry-Pool/nami-wallet#98]
I'm trying to get transactions using `getUtxos` function from wallet but everytime I recieved only 8 transactions despite I have 30 asssets (each from separate transaciton). I tried to provide bigger limit and also different pages but I get either up to 8 transactions.

**Comment by pascallapointe** [comment]
The coin-selection is doing UTxO set management each time you make a transaction using Nami.
In short, it consolidate your multiple small UTxO in bigger one to keep the set healthy.

Unless you never made any transaction with Nami, it is normal for the UTxO set to be lower than the received transaction.

From here, can you confirm that there is missing assets from the UTxO set returned by the wallet?
My suggestion would be to use blockfrost API to inspect your UTxO set under your Nami address:  https://cardano-mainnet.blockfrost.io/api/v0/addresses/{address}/utxos

This way you could confirm if Nami return all UTxO or not

**Comment by rosieks** [comment]
Ok, got it - Blockfrost also returns 8. Sorry for false alarm
